<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'register','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">   
   		if(this.validate()) {
			branch_id = dijit.byId('branch').get('value');
			if(branch_id==-1 || branch_id==0){
			 	alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?> !!! ");
			 	dijit.byId("branch").focus();
			 	return false;
			}
			year = dijit.byId('study_year').get('value');
			if(year==-1 || year==0){
				alert("<?php echo $tr->translate("PLEASE_SELECT_ACADEMIC_YEAR")?> !!! ");
			 	dijit.byId("study_year").focus();
			 	return false;
			}
			loadingBlock();
			dijit.byId('save_close').set('disabled',true);
			return true;
   		}else {
			return false;
  	 	}
		</script>

	<table  cellspacing="10" style="margin: 0 auto; width: 100%;white-space:nowrap;">
		<tr>
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;" cellspacing="5" >
						<tr>
							<td ><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select  type="text" name="branch" id="branch" onchange="getYearByBranch();" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1"><?php echo $tr->translate("SELECT_BRANCH");?></option>
								<?php if(!empty($this->branch_id)){foreach ($this->branch_id as $branch){?>
									<option value="<?php echo $branch['id'];?>" <?php if($branch['id']==$this->degree_row['branch_id']){echo 'selected="selected"';}?>><?php echo $branch['name'];?></option>
								<?php }}?>
								</select>
								<input type="hidden" name="pay_id" id="pay_id" value="<?php echo $this->degree_row['id'];?>" dojoType="dijit.form.TextBox" >
							</td>
						</tr>
						<tr>
							<td width="20%"><?php echo $tr->translate("STUDENT_TYPE");?></td>
							<td width="80%"><?php  echo $register->getElement('student_type');?>
								<?php echo $register->getElement('ids'); ?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<div id="student_old">
									<select name="old_studens" id="old_studens" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_code)){foreach($this->old_stu_code as $stu_code){?>
											<option value="<?php echo $stu_code['stu_id']?>"><?php echo $stu_code['stu_code']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="id_stu"><?php echo $register->getElement('stu_id');?></div>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="student_old_name">
									<select name="old_stu_name" id="old_stu_name" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_name)){foreach($this->old_stu_name as $stu_name){?>
											<option value="<?php echo $stu_name['stu_id']?>"><?php echo $stu_name['name']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("DOB");?></td>
						<td><input type="text"  class="fullside" name="dob" id="dob" value="<?php echo $this->degree_row['dob'];?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							<td><input type="text"  class="fullside" name="address" id="address" value="<?php echo $this->degree_row['address'];?>" dojoType="dijit.form.TextBox" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" id="phone" value="<?php echo $this->degree_row['tel'];?>" class="fullside" dojoType="dijit.form.TextBox" /></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;" cellspacing="5" >
						<tr>
							<td width="20%"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td width="80%"><input id="study_year" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
							<td><input id="dept" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
							<td><input id="grade" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("ROOM_NAME");?><label class="red">*</label></td>
							<td>
								<select name="room" id="room" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="-1"><?php echo $tr->translate("SELECT_ROOM")?></option>
									<?php if(!empty($this->room)){foreach ($this->room as $room){?>
										<option value="<?php echo $room['id']?>" <?php if($room['id']==$this->degree_row['room_id']){echo "selected='selected'";}?>><?php echo $room['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("TIME");?></td>
							<td>
							    <select dojoType="dijit.form.FilteringSelect" class="fullside" id="study_hour" name="study_hour" required="false">
									<option value="select time">select time</option>
									<?php if(!empty($this->all_time)){foreach($this->all_time as $time){?>
										<option value="<?php echo $time['name']?>" <?php if($time['name'] == $this->degree_row['time']){echo "selected='selected'";}?>><?php echo $time['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><?php echo $register->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><?php echo $register->getElement('end_date');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("NOTE");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
						</tr>
						<tr>	
							<td colspan="2"><?php echo $this->degree_row['create_date'];?></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;" cellspacing="5" >
						
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td width="80%"><?php echo $register->getElement('reciept_no');?>
								<?php echo $register->getElement('id');?><?php echo $register->getElement('parent_id');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('payment_term');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('tuitionfee');?>
								<input type="hidden" name="price_per_section" id="price_per_section" value="<?php echo $this->degree_row['price_per_sec'];?>" dojoType="dijit.form.TextBox" >
							</td>
						</tr>
						<tr>
							<td>
								<div id="label_amount">
									<?php echo $tr->translate("AMOUNT");?>
								</div>
							</td>
							<td>
								<div id="amount_section">
									<input name="amount_section" id="amount_section" onkeyup="getTotale();" dojoType="dijit.form.TextBox" value="<?php echo $this->degree_row['qty'];?>" class="fullside" type="text"/>
								</div>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISCOUNT");?></td>
							<td>
								<table width="100%" style="white-space: nowrap;">
									<tr>
										<td width="10%">(%)&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount');?></td>
										<td width="10%">&nbsp;&nbsp;($)&nbsp;&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount_fix');?></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("ADMIN_FEE");?></td>
							<td><?php echo $register->getElement('addmin_fee');?></td>	
						</tr>
						<tr>	
							<td><?php echo $tr->translate("MATERIAL_FEE");?></td>
							<td><?php echo $register->getElement('material_fee');?></td>	
						</tr>
						<tr>	
							<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
							<td><?php echo $register->getElement('total');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
							<td><?php echo $register->getElement('books');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("BALANCE");?></td>
							<td><?php echo $register->getElement('remaining');;?></td>
						</tr>
						
						<tr>	
							<td><?php echo $tr->translate("CREATE_DATE");?></td>
							<td><?php echo $register->getElement('create_date');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("វេន");?></td>
							<td>
								<select name="shift" id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="1" <?php if($this->degree_row['shift']==1){echo "selected='selected'";}?>>វេនទី1</option>
									<option value="2" <?php if($this->degree_row['shift']==2){echo "selected='selected'";}?>>វេនទី2</option>
									<option value="3" <?php if($this->degree_row['shift']==3){echo "selected='selected'";}?>>វេនទី3</option>
								</select>
							</td>
						</tr>
						<tr><td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
							<td><?php echo $register->getElement('payment_method');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAYIMENT_NOTE");?></td>
							<td><?php echo $register->getElement('note_payment');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("is start");?></td>
							<td>
								<input name="is_start" id="is_start" dojoType="dijit.form.TextBox" value="<?php echo $this->degree_row['is_start'];?>" class="fullside" />
							</td>
						</tr>
					</table>	
				</fieldset>		
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="center">
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" value="1" name="is_void" id="is_void" <?php if($this->degree_row['is_void']==1){echo 'onclick="return false;"';}?> dojoType="dijit.form.CheckBox"  /> Void
			</td>
		</tr>
		<tr>
			<td colspan="3">
				<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
						<tr id="head-title" class="head-td" align="right"></tr>
				</table>
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="right">
				<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
					<tr>
						<td ><?php echo $tr->translate("EXCHANGE_RATE")." (៛)";?></td>
						<td align="right">
							<input type="text" name="ex_rate" id="ex_rate" readonly value="<?php echo $this->degree_row['exchange_rate'] ;?>" dojoType="dijit.form.NumberTextBox" />
						</td>
					</tr>
					<tr>
						<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
						<td align="right"><input type="text" readonly="readonly" value="<?php echo $this->degree_row['grand_total_payment'] ;?>" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
						<td align="right"><input  type="text" readonly="readonly" value="<?php echo $this->degree_row['grand_total_payment_in_riel'] ;?>" name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
						<td align="right"><input  type="text" readonly="readonly" value="<?php echo $this->degree_row['grand_total_paid_amount'] ;?>" onkeyup="calculatBalanceAndReturn();" name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td align="right"><input type="text"  readonly="readonly" value="<?php echo $this->degree_row['grand_total_balance'] ;?>" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
				</table>
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="center">
				<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate("GO_EDIT");?>"  dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconSave" />
			</td>
		</tr>
		
	</table>	
</form>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require('dojox.form.BusyButton');
	dojo.require("dijit.form.Textarea");
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	dojo.ready(function(){
		
		changControll();

		new dijit.form.FilteringSelect({
		    store: dept_store,
		    autoComplete: true,                        
		    required: false,
		    id: "dept",
		    name: "dept",           
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_DEGREE")?>",          
		    onChange: function() {  
		    	dept_id = dijit.byId('dept').get('value');
		    	dijit.byId('grade').attr('value','');
		    	getallModel(dept_id,a=''); 
		    }
		}, "dept");
		new dijit.form.FilteringSelect({
		    //store: dept_store,
		    autoComplete: true,  
			required: false,			
		    id: "grade",
		    name: "grade",           
		    class: 'fullside', 
		    placeHolder:"<?php echo $tr->translate("SELECT_GRADE")?>",          
		    onChange: function() {  
		    }
		}, "grade");
		dijit.byId('dept').attr('value','<?php echo $this->degree_row['degree'];?>');


		new dijit.form.FilteringSelect({
		    autoComplete: true, 
			required: false,
		    id: "study_year",
		    name: "study_year",           
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR")?>",          
		    onChange: function() {  
		    }
		}, "study_year");
		getYearByBranch();
		setReadonlyPageEdit();
		
	});	


	var year_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_year = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'get-year-by-branch')); ?>';
	function getYearByBranch(){
		branch_id = dijit.byId('branch').get('value');
			dojo.xhrPost({
				url:url_year,
				content:{
					'branch_id':branch_id,
					'time':2,// fulltime
				},
				handleAs:"json",
				load: function(data) {
					year_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('study_year').set('store',year_store);   
				    dijit.byId('study_year').attr('value','<?php echo $this->degree_row['academic_year'];?>');
				},
				error: function(err) {
				}
			});
	}

	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'accounting','controller'=>'register','action'=>'get-grade')); ?>';
	function getallModel(dept_id,a){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);  
				    dijit.byId('grade').attr('value','<?php echo $this->degree_row['grade']?>');
				    if(a!=""){
				    	dijit.byId('grade').attr('value',a);
			        } 
				},
				error: function(err) {
				}
			});
	}
	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id){
		if(dept_id==''){
			return false;
		}
		dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					  dijit.byId('stu_id').attr('value',data);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}
	function paymentTerm(){
		old_grade='<?php echo $this->degree_row['grade'];?>';
    	old_payterm='<?php echo $this->degree_row['payment_term'];?>';
    	grade=dijit.byId('grade').get('value');
    	payterm=dijit.byId('payment_term').get('value');
    	if(old_grade==grade && old_payterm==payterm){
    		defaultPayment();
	    }else{
	    	generat=dijit.byId('study_year').get('value');
			payment_term=dijit.byId('payment_term').get('value');
			grade=dijit.byId('grade').get('value');
			session=dijit.byId('session').get('value');
			if(generat!='' && payment_term !='' && grade !='' && session !=''){
				getPaymentTerms(generat,payment_term,grade,session);
			}
			dijit.byId('discount').attr('value','0');
	    	dijit.byId('books').attr('value','0');
	    	dijit.byId('addmin_fee').attr('value','0');
	    	dijit.byId('remaining').attr('value','0');
	    	dijit.byId('remark').attr('value','0');
	    	dijit.byId('not').attr('value',''); 
		}
	}
	function paymentTerms(){
		generat=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		grade=dijit.byId('grade').get('value');
		session=dijit.byId('session').get('value');
		if(generat!='' && payment_term !='' && grade !='' && session !=''){
			getPaymentTerms(generat,payment_term,grade,session);
		}
	}
	
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-payment-term')); ?>';
	function getPaymentTerms(generat,pay,grade,session){
		dojo.xhrPost({
			url:url_getpaymentterm,
			content:{
				'generat_id':generat,
				'pay_id':pay,
				'grade_id':grade,
				'session':session
				},
			handleAs:"json",
			load: function(data) {
				  if(data){
					  dijit.byId('tuitionfee').attr('value',data.tuition_fee);
					  dijit.byId('total').attr('value',data.tuition_fee);
					  dijit.byId('books').attr('value',data.tuition_fee);
					  dijit.byId('price_per_section').attr('value',data.tuition_fee);
				  }else {
					
				  }
			 
			},
			error: function(err) {
			}
		});
	}
	function defaultPayment(){
		
		dijit.byId('tuitionfee').attr('value','<?php echo $this->degree_row['tuition_fee'];?>');
    	dijit.byId('total').attr('value','<?php echo $this->degree_row['total_payment'];?>');
    	dijit.byId('discount').attr('value','<?php echo $this->degree_row['discount_percent'];?>');
    	dijit.byId('books').attr('value','<?php echo $this->degree_row['paid_amount'];?>');
    	dijit.byId('addmin_fee').attr('value','<?php echo $this->degree_row['admin_fee'];?>');
    	dijit.byId('remaining').attr('value','<?php echo $this->degree_row['balance_due'];?>');
    	dijit.byId('remark').attr('value','<?php echo $this->degree_row['other_fee'];?>');
    	dijit.byId('not').attr('value','<?php echo $this->degree_row['note'];?>');
    	dijit.byId('study_hour').attr('value','<?php echo $this->degree_row['time'];?>');
    	dijit.byId('price_per_section').attr('value','<?php echo $this->degree_row['price_per_sec'];?>');
    	displayAmountSection();
		netTotal();
	}

	//set value totale 
	function getTotale(){
		tuitionfee = dijit.byId('tuitionfee').get('value');
		amount_section = dijit.byId('amount_section').get('value');
		tuitionfee = tuitionfee * amount_section;
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		discount = isNaN(discount)?0:discount;
		discount_fix=dijit.byId('discount_fix').get('value');
		discount_fix = isNaN(discount_fix)?0:discount_fix;
		pc=discount/100;
		ds=(tuitionfee-discount_fix)*pc;
		old_totale=(tuitionfee-discount_fix) - ds;
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		addmin_fee=dijit.byId('addmin_fee').get('value');
		addmin_fee=isNaN(addmin_fee)?0:addmin_fee;
		material_fee=dijit.byId('material_fee').get('value');
		material_fee=isNaN(material_fee)?0:material_fee;
		totals = parseFloat(old_totale) + parseFloat(remark) + parseFloat(addmin_fee) + parseFloat(material_fee);
		
		dijit.byId('total').attr('value',totals.toFixed(2));
		dijit.byId('books').attr('value',totals.toFixed(2));
		
		getRemaining();
		netTotal();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
	}
	function getDisccount(){
		books=dijit.byId('books').get('value');
		books=isNaN(books)?0:books;
	
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			   dijit.byId('total').attr('value',totale.toFixed(2));
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
			}
	}
	
	function netTotal(){
		var netTotal=0;
		var netPaidAmount=0;
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
		ex_rate = dijit.byId('ex_rate').get('value');
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
	}
	
	function setReadonlyPageEdit(){
		dijit.byId("branch").set('readOnly',true);
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("old_stu_name").set('readOnly',true);
		dijit.byId("old_studens").set('readOnly',true);
		dijit.byId("en_name").set('readOnly',true);
		dijit.byId("kh_name").set('readOnly',true);
		dijit.byId("sex").set('readOnly',true);
		dijit.byId("dob").set('readOnly',true);
		dijit.byId("phone").set('readOnly',true);
		dijit.byId("address").set('readOnly',true);
		<?php if($this->user_type>2){//1=admin , 2=account manager ?>
			dijit.byId("reciept_no").set('readOnly',true);
			dijit.byId("create_date").set('readOnly',true);
			dijit.byId("start_date").set('readOnly',true);
			dijit.byId("end_date").set('readOnly',true);
			dijit.byId("tuitionfee").set('readOnly',true);
			dijit.byId("payment_term").set('readOnly',true);
			dijit.byId("amount_section").set('readOnly',true);
			dijit.byId("discount").set('readOnly',true);
			dijit.byId("discount_fix").set('readOnly',true);
			dijit.byId("remark").set('readOnly',true);
			dijit.byId("addmin_fee").set('readOnly',true);
			dijit.byId("material_fee").set('readOnly',true);
			dijit.byId("books").set('readOnly',true);
			dijit.byId("not").set('readOnly',true);
		<?php }?>
	}
	
	function displayAmountSection(){
		payment_term = dijit.byId('payment_term').get('value');
		if(payment_term==5){
			document.getElementById('amount_section').style.display="block";
			document.getElementById('label_amount').style.display="block";
			
		}else{
			document.getElementById('amount_section').style.display="none";
			document.getElementById('label_amount').style.display="none";
		}
	}
	function changControll(){
		 document.getElementById('student_old').style.display="block";
		 document.getElementById('student_old_name').style.display="block";
		 document.getElementById('id_stu').style.display="none";
		 document.getElementById('name_stu').style.display="none";
	}
	function setID(){
		stu_id = dijit.byId('old_stu_name').get('value');
		dijit.byId('old_studens').attr('value',stu_id);
	}
	function clearControll(){
		dijit.byId('kh_name').attr('value','');
		dijit.byId('en_name').attr('value','');
	}
</script>