<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_REGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
		year = dijit.byId('study_year').get('value');
    	if(year==-1 || year==0){
			alert("<?php echo $tr->translate("PLEASE_SELECT_ACADEMIC_YEAR")?> !!! ");
        	dijit.byId("study_year").focus();
        	return false;
    	}
		loadingBlock();
	    dijit.byId('save_close').set('disabled',true);
		return true;
   }else {
		return false;
   }
</script>
	<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
		<tr>
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;white-space: nowrap;" cellspacing="5" >
						<tr>
							<td><?php echo $tr->translate("STUDENT_TYPE");?></td>
							<td><?php  echo $register->getElement('student_type');?>
								<?php echo $register->getElement('ids'); ?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<div id="student_old">
									<select name="old_studens" id="old_studens" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_code)){foreach($this->old_stu_code as $stu_code){?>
											<option value="<?php echo $stu_code['stu_id']?>"><?php echo $stu_code['stu_code']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="id_stu"><?php echo $register->getElement('stu_id');?></div>
								<div id="drop_stu_code"><?php echo "";?></div>
								<input type="hidden" name="pay_id" id="pay_id" value="<?php echo $this->degree_row['payment_id']?>" dojoType="dijit.form.TextBox" />	
							</td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="student_old_name">
									<select name="old_stu_name" id="old_stu_name" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_name)){foreach($this->old_stu_name as $stu_name){?>
											<option value="<?php echo $stu_name['stu_id']?>"><?php echo $stu_name['name']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
								<div id="drop_stuname"><?php echo "";?></div>
								
							</td>
						</tr>
						<tr>
							<td width="20%"><?php echo $tr->translate("NAME_KH");?></td>
							<td width="80%"><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
						</tr>	
						<tr>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input type="text"  class="fullside" name="dob" id="dob" value="<?php echo $this->degree_row['dob'];?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							<td><input type="text"  class="fullside" name="address" id="address" value="<?php echo $this->degree_row['address'];?>" dojoType="dijit.form.TextBox" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" id="phone" value="<?php echo $this->degree_row['tel'];?>" class="fullside" dojoType="dijit.form.TextBox" /></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;white-space: nowrap;" cellspacing="5" >
						<tr>
							<td width="20%"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td width="80%"><?php echo $register->getElement('study_year');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
							<td><input id="dept" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
							<td><input id="grade" /></td>
						</tr>
						<tr>						
							<td><?php echo $tr->translate("ROOM_NAME");?><label class="red">*</label></td>
							<td>
								<select name="room" id="room" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="-1"><?php echo $tr->translate("SELECT_ROOM")?></option>
									<?php if(!empty($this->room)){foreach ($this->room as $room){?>
										<option value="<?php echo $room['id']?>" <?php if($room['id']==$this->degree_row['room_id']){echo "selected='selected'";}?>><?php echo $room['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("TIME");?></td>
							<td>
							    <select dojoType="dijit.form.FilteringSelect" class="fullside" id="study_hour" name="study_hour" required="false">
									<option value="select time"><?php echo $tr->translate("SELECT_TIME")?></option>
									<?php if(!empty($this->all_time)){foreach($this->all_time as $time){?>
										<option value="<?php echo $time['name']?>" <?php if($time['name'] == $this->degree_row['time']){echo "selected='selected'";}?>><?php echo $time['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><?php echo $register->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><?php echo $register->getElement('end_date');?></td>
						</tr>
						</tr>
							<td><?php echo $tr->translate("NOTE");?></td>
							<td><?php echo $register->getElement('not');?></td>
						</tr>
						
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;white-space: nowrap;" cellspacing="5" >
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td width="80%"><?php echo $register->getElement('reciept_no');?>
								<?php echo $register->getElement('id');?><?php echo $register->getElement('parent_id');?>
							</td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('payment_term');?></td>
						</tr>
						</tr>	
							<td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('tuitionfee');?></td>
						</tr>
						<input type="hidden" id="degree_type" name="degree_type" value="<?php echo $this->degree_row['degree_type'];?>" dojoType="dijit.form.TextBox"/>
						<input type="hidden" name="price_per_section" id="price_per_section" value="<?php echo $this->degree_row['price_per_sec'];?>" dojoType="dijit.form.TextBox" >
						<tr>
							<td>
								<div id="label_amount">
									<?php echo $tr->translate("AMOUNT");?>
								</div>
							</td>
							<td>
								<div id="amount_section">
									<input name="amount_section" id="amount_section" onkeyup="getTotale();" dojoType="dijit.form.TextBox" value="<?php echo $this->degree_row['qty'];?>" class="fullside" type="text"/>
								</div>
							</td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("DISCOUNT");?></td>
							<td>
								<table width="100%" style="white-space: nowrap;">
									<tr>
										<td width="10%">(%)&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount');?></td>
										<td width="10%">&nbsp;&nbsp;($)&nbsp;&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount_fix');?></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("ADMIN_FEE");?></td>
							<td><?php echo $register->getElement('addmin_fee');?></td>	
						</tr>
						<tr>	
							<td><?php echo $tr->translate("MATERIAL_FEE");?></td>
							<td><?php echo $register->getElement('material_fee');?></td>	
						</tr>
						<tr>	
							<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
							<td><?php echo $register->getElement('total');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
							<td><?php echo $register->getElement('books');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("BALANCE");?></td>
							<td><?php echo $register->getElement('remaining');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
							<td><?php echo $register->getElement('payment_method');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAYIMENT_NOTE");?></td>
							<td><?php echo $register->getElement('note_payment');?></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center">
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" value="1" name="is_void" id="is_void" <?php if($this->row['is_void']==1){echo 'onclick="return false;"';}?> dojoType="dijit.form.CheckBox"  /> Void
			</td>
		</tr>
		<tr>
			<td colspan="1">
				<input type="text" class="fullside" name="readmoney" id="readmoney" readOnly dojoType="dijit.form.TextBox" />
			</td>
		
			<td colspan="2" align="right">
				<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
					<tr>
						<td ><?php echo $tr->translate("EXCHANGE_RATE")." (៛)";?></td>
						<td align="right">
							<input type="text" name="ex_rate" id="ex_rate" readonly value="<?php echo $this->degree_row['exchange_rate'] ;?>" dojoType="dijit.form.NumberTextBox" />
						</td>
					</tr>
					<tr>
						<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
						<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
						<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
						<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="center">
				<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate("GO_EDIT");?>"  dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
				 
				<input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="busyButton" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	dojo.ready(function(){
		changControll();
		
		new dijit.form.FilteringSelect({
			store: dept_store,
			autoComplete: true,                        
			required: true,
			id: "dept",
			name: "dept",           
			class: 'fullside',  
			placeHolder:"Selected Class",          
			onChange: function() {  
				dept_id = dijit.byId('dept').get('value');
				dijit.byId('grade').attr('value','');
				getallModel(dept_id,a=''); 
			}
		}, "dept");
		new dijit.form.FilteringSelect({
			autoComplete: true,                        
			id: "grade",
			name: "grade",           
			class: 'fullside', 
			placeHolder:"Selected Grade",          
			onChange: function() {  
				paymentTerm();
			}
		}, "grade");
		dijit.byId('dept').attr('value','<?php echo $this->degree_row['degree'];?>');
		
		setReadonlyPageEdit();
		
		degree_type = '<?php echo $this->degree_row['degree_type'];?>';
		if(degree_type==1){
			document.getElementById('label_type').innerHTML = '- តម្លៃសិក្សាខាងលើ សម្រាប់តែសេវាសិក្សាចំណេះទូទៅភាសាខ្មែរតែប៉ុណ្ណោះ/This fee is for Khmer program service only.';
		}else{
			document.getElementById('label_type').innerHTML = '- តម្លៃសិក្សាខាងលើ សម្រាប់តែសេវាសិក្សាភាសាអង់គ្លេសពេញម៉ោងតែប៉ុណ្ណោះ/This fee is for full-time english service only.';
		}
	});	
	
	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
	function getallModel(dept_id,a){
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);  
			    dijit.byId('grade').attr('value','<?php echo $this->degree_row['grade']?>');
			    if(a!=""){
			    	dijit.byId('grade').attr('value',a);
		        } 
			},
			error: function(err) {
			}
		});
	}
	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id){
		if(dept_id==''){
			return false;
		}
		dojo.xhrPost({
			url:url_getstuno,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('stu_id').attr('value',data);   
			},
			error: function(err) {
			}
		});
	}
	function paymentTerm(){
		old_grade='<?php echo $this->degree_row['grade'];?>';
    	old_payterm='<?php echo $this->degree_row['payment_term'];?>';
    	grade=dijit.byId('grade').get('value');
    	payterm=dijit.byId('payment_term').get('value');
    	if(old_grade==grade && old_payterm==payterm){
    		defaultPayment();
	    }else{
	    	generat=dijit.byId('study_year').get('value');
			payment_term=dijit.byId('payment_term').get('value');
			grade=dijit.byId('grade').get('value');
			session=dijit.byId('session').get('value');
			if(generat!='' && payment_term !='' && grade !='' && session !=''){
				getPaymentTerms(generat,payment_term,grade,session);
			}
			dijit.byId('discount').attr('value','0');
	    	dijit.byId('books').attr('value','0');
	    	dijit.byId('addmin_fee').attr('value','0');
	    	dijit.byId('remaining').attr('value','0');
	    	dijit.byId('remark').attr('value','0');
	    	dijit.byId('not').attr('value',''); 
		}
	}
	function paymentTerms(){
		generat=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		grade=dijit.byId('grade').get('value');
		session=dijit.byId('session').get('value');
		if(generat!='' && payment_term !='' && grade !='' && session !=''){
			getPaymentTerms(generat,payment_term,grade,session);
		}
	}
	
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-payment-term')); ?>';
	function getPaymentTerms(generat,pay,grade,session){
			dojo.xhrPost({
				url:url_getpaymentterm,
				content:{
					'generat_id':generat,
					'pay_id':pay,
					'grade_id':grade,
					'session':session
					},
				handleAs:"json",
				load: function(data) {
			      if(data){
			    	  dijit.byId('tuitionfee').attr('value',data.tuition_fee);
				      dijit.byId('total').attr('value',data.tuition_fee);
				      dijit.byId('books').attr('value',data.tuition_fee);
			      }
				},
				error: function(err) {
				}
			});
	}
	
	function setReadonlyPageEdit(){
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("old_stu_name").set('readOnly',true);
		dijit.byId("old_studens").set('readOnly',true);
		dijit.byId("en_name").set('readOnly',true);
		dijit.byId("kh_name").set('readOnly',true);
		dijit.byId("sex").set('readOnly',true);
		dijit.byId("dob").set('readOnly',true);
		dijit.byId("phone").set('readOnly',true);
		dijit.byId("address").set('readOnly',true);
		dijit.byId("study_year").set('readOnly',true);
		dijit.byId("room").set('readOnly',true);
		dijit.byId("dept").set('readOnly',true);
		dijit.byId("grade").set('readOnly',true);
		dijit.byId("tuitionfee").set('readOnly',true);
		dijit.byId("session").set('readOnly',true);
		dijit.byId("study_hour").set('readOnly',true);
		dijit.byId("payment_term").set('readOnly',true);
		dijit.byId("amount_section").set('readOnly',true);
		dijit.byId("discount").set('readOnly',true);
		dijit.byId("discount_fix").set('readOnly',true);
		dijit.byId("remark").set('readOnly',true);
		dijit.byId("addmin_fee").set('readOnly',true);
		dijit.byId("material_fee").set('readOnly',true);
		dijit.byId("books").set('readOnly',true);
		dijit.byId("not").set('readOnly',true);
		dijit.byId("remaining").set('readOnly',true);
		dijit.byId("reciept_no").set('readOnly',true);
		dijit.byId("stu_id").set('readOnly',true);
		dijit.byId("start_date").set('readOnly',true);
		dijit.byId("end_date").set('readOnly',true);
		
		<?php if($this->user_type=1 || $this->user_type==2 || $this->user_type==17){?> // 17=School Principle
			dijit.byId("start_date").set('readOnly',false);
			dijit.byId("end_date").set('readOnly',false);
		<?php }?>
	}
	
	function defaultPayment(){
		dijit.byId('tuitionfee').attr('value','<?php echo $this->degree_row['fee'];?>');
    	dijit.byId('total').attr('value','<?php echo $this->degree_row['total_payment'];?>');
    	dijit.byId('discount').attr('value','<?php echo $this->degree_row['discount_percent'];?>');
    	dijit.byId('books').attr('value','<?php echo $this->degree_row['paid_amount'];?>');
    	dijit.byId('addmin_fee').attr('value','<?php echo $this->degree_row['admin_fee'];?>');
    	dijit.byId('remaining').attr('value','<?php echo $this->degree_row['balance_due'];?>');
    	dijit.byId('remark').attr('value','<?php echo $this->degree_row['other_fee'];?>');
    	dijit.byId('not').attr('value','<?php echo $this->degree_row['note'];?>');
    	dijit.byId('study_hour').attr('value','<?php echo $this->degree_row['time'];?>');
		dijit.byId('price_per_section').attr('value','<?php echo $this->degree_row['price_per_sec'];?>');
		netTotal();
	}
	
	function netTotal() {
		var netTotal=0;
		var netPaidAmount=0;
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		readMoneyInKhmer(grand_total_paid.toFixed(2));
	}
	
	//get price balance 
	function getBalanceOldStudent(){
		old_studens=old_studens=dijit.byId('old_studens').get('value');
		if(old_studens != -1){
			getBalancePrice(1,old_studens);
		}
	}
	//get price balance
	var url_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-banlance-price')); ?>';
	function getBalancePrice(servce_id,student_id){
		dojo.xhrPost({
			url:url_balance,
			content:{
				'servce_id':servce_id,
				'student_id':student_id,
				},
			handleAs:"json",
			load: function(data) {
		      if(data){
		    	  dijit.byId('tuitionfee').attr('value',data.price_fee);
		    	  dijit.byId('ids').attr('value',data.id);
		     	  dijit.byId('total').attr('value',data.price_fee);
		    	  dijit.byId('books').attr('value',data.price_fee);
		    	  dijit.byId('not').attr('value',data.sms);
		    	  dijit.byId('remaining').attr('value','0');
		     }else {
		    	 dijit.byId('ids').attr('value','');
		    	 dijit.byId('not').attr('value','');
		    	 paymentTerms();
		      }
			},
			error: function(err) {
			}
		});
	}
	//set value totale 
	function getTotale(){
		//old % totale
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		old_totale=tuitionfee - ds;
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		addmin_fee=dijit.byId('addmin_fee').get('value');
		addmin_fee=isNaN(addmin_fee)?0:addmin_fee;
		totals=parseFloat(old_totale)+parseFloat(remark)+parseFloat(addmin_fee);
		dijit.byId('total').attr('value',totals.toFixed(2));
		dijit.byId('books').attr('value',totals.toFixed(2));
		getRemaining();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
		  CheckAmount();
	}
	function getDisccount(){
		books=dijit.byId('books').get('value');
		books=isNaN(books)?0:books;
	
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			 dijit.byId('total').attr('value',totale.toFixed(2));
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
			}
	}
	
	var url_getstu_info = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-studentinfo')); ?>';
	function getStudentBYId(){
		   student_id = dijit.byId("stu_id").get('value');
		   if(student_id==''){
			   return false;
			   }
				dojo.xhrPost({
				   content : {'student_card':  student_id},
				    url: url_getstu_info,			    
					handleAs:"json",
				    load: function(response) {	
					    dijit.byId("kh_name").attr('value',response.stu_khname);
					    dijit.byId("en_name").attr('value',response.stu_enname);
					    dijit.byId('sex').set('value', response.sex);
					    dijit.byId("phone").attr('value',response.phone);
					    dijit.byId("metion").attr('value',response.mention);
					    dijit.byId('year').attr('value',response.year);
					    dijit.byId('degree').set('value', response.degree);
					    dijit.byId('batch').set('value',response.batch);
					    dijit.byId('dept').set('value',response.faculty_id);
					    dijit.byId('session').set('value',response.session);
				    },
				    error: function(e) {
				    }
				});
	}

	//set hour defuale
	function setHourDefaul(){
		dept=dijit.byId('dept').get('value');
		session=dijit.byId('session').get('value');
		if(dept==1 && session==1){
			dijit.byId('study_hour').attr('value','7:30AM - 10:50AM');
		}else if(dept==1 && session==2){
			dijit.byId('study_hour').attr('value','1:30PM - 4:50PM');
		}else if(session==1){
			dijit.byId('study_hour').attr('value','7:00AM - 11:00AM');
		}else if(session==2){
			dijit.byId('study_hour').attr('value','1:00PM - 5:00PM');
		}else if(session==5){
			dijit.byId('study_hour').attr('value','7:30AM - 4:30PM');
		}else{
			dijit.byId('study_hour').attr('value','');
		}
	}


	function changControll(){
	 student_type=dijit.byId('student_type').get('value');
	 document.getElementById('student_old').style.display="block";
	 document.getElementById('student_old_name').style.display="block";
	 document.getElementById('id_stu').style.display="none";
	 document.getElementById('name_stu').style.display="none";
	 document.getElementById('drop_stu_code').style.display="none";
	 document.getElementById('drop_stuname').style.display="none";
	}

	function setID(type){
		if(type==1){
			stu_id = dijit.byId('old_stu_name').get('value');
			dijit.byId('old_studens').attr('value',stu_id);
		}else{
			
		}
	}

	function clearControll(){
		dijit.byId('kh_name').attr('value','');
		dijit.byId('en_name').attr('value','');
	}
	///get Gerneral old student
	function getGeneralOldStudentById(){
		var url_getalldstudent = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-general-old-student')); ?>';
		student_id=dijit.byId('old_studens').get('value');
		dijit.byId('old_stu_name').attr('value',student_id);
			dojo.xhrPost({
				url:url_getalldstudent,
				content:{
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					   if(data){
						dijit.byId('kh_name').attr('value',data.stu_khname);
						dijit.byId('en_name').attr('value',data.stu_enname);
						dijit.byId('sex').attr('value',data.sex);
						dijit.byId('dept').attr('value',data.degree);
						getallModel(data.degree,data.grade);
					  }else {
						alert('Student Id not found!');
						dijit.byId('kh_name').attr('value','');
						dijit.byId('en_name').attr('value','');
						dijit.byId('sex').attr('value','');
						dijit.byId('dept').attr('value','');
						dijit.byId('grade').attr('value','');
					  } 
				},
				error: function(err) {
				}
			});
	}
	
// printSave for receipt data only	
	function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
			 degree_type = dijit.byId('degree_type').get('value');
			 if(degree_type==1){
				 label="ចំណេះទូទៅភាសាខ្មែរ";
			 }else{
				 label="Full Time English";
			 }
			 
			// dojo.byId("lb_receipt_type").innerHTML = label;
			 stu_type = dijit.byId('student_type').get('value');
			 if(stu_type==1){
				 dojo.byId("lb_stu_type").innerHTML = "សិស្សថ្មី/New Stu.";
			 }else{
				 dojo.byId("lb_stu_type").innerHTML = "សិស្សចាស់/Old Stu.";;
			 }
			new_receipt_no = dijit.byId("reciept_no").get('value');
			dojo.byId("lb_stu_id").innerHTML = dijit.byId("old_studens").attr('displayedValue');
			
			 dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value');
			 dojo.byId("lb_en_name").innerHTML = dijit.byId("en_name").get('value');
			 dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
			 dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
			 room_id = dijit.byId("room").get('value');
			 if(room_id>0){
				dojo.byId("lb_room").innerHTML = dijit.byId('room').attr('displayedValue');
			 }else{
				dojo.byId("lb_room").innerHTML = '';
			 }
			 
			 dojo.byId("lb_hour").innerHTML = dijit.byId('study_hour').attr('displayedValue');
			 dojo.byId("lb_dob").innerHTML = dijit.byId('dob').attr('displayedValue');
			 dojo.byId("lb_grade").innerHTML = dijit.byId("grade").attr('displayedValue');
			 dojo.byId("lb_note").innerHTML = dijit.byId("not").attr('value');

			 payment_term = dijit.byId('payment_term').get('value');
			 tuitionfee = dijit.byId('tuitionfee').get('value');
			 amount_section = dijit.byId('amount_section').get('value');
			 study_fee = tuitionfee * amount_section;
			 dojo.byId("lb_study_fee").innerHTML = "$ "+study_fee.toFixed(2);
			 dis_percent = dijit.byId('discount').get('value');
			 dis_percent = isNaN(dis_percent)?0:dis_percent;
			 dis_fix = dijit.byId('discount_fix').get('value');
			 dis_fix = isNaN(dis_fix)?0:dis_fix;
			 
			 discount=0;
			 if(dis_percent>0 && dis_fix>0){
				discount = dis_percent + " %  + " + dis_fix + " $"; 
			 }else{
				 if(dis_percent>0){
					discount = dis_percent + " %";
				 }else{
					discount = dis_fix + " $";
				 }
			 }
			 dojo.byId("lb_discount").innerHTML = discount;
			 after_discount = (study_fee - dis_fix) - ((study_fee - dis_fix) * (dis_percent/100));
			 dojo.byId("lb_total_payment").innerHTML = "$ " + after_discount.toFixed(2);
			 admin_fee = dijit.byId("addmin_fee").get('value');
			 admin_fee = isNaN(admin_fee)?0:admin_fee;
			 dojo.byId("lb_admin_fee").innerHTML = "$ "+admin_fee;
			 material_fee = dijit.byId("material_fee").get('value');
			 material_fee = isNaN(material_fee)?0:material_fee;
			 dojo.byId("lb_total_product_fee").innerHTML = "$ "+material_fee;
			 dojo.byId("lb_grand_total").innerHTML = "$ "+dijit.byId('grand_total').get('value');
			 dojo.byId("lb_total_balance").innerHTML = "$ "+dijit.byId('total_balance').get('value');
			 dojo.byId("lb_total_paid").innerHTML = " &nbsp;&nbsp;$ "+dijit.byId('total_received').get('value');
			 dojo.byId("lb_read_money").innerHTML = dijit.byId('readmoney').get('value');
			 
			pay_term = dijit.byId('amount_section').get('value') + " " + dijit.byId('payment_term').attr('displayedValue');
			dojo.byId("lb_payment_term").innerHTML = pay_term;
			
			var b = new Date(dijit.byId("start_date").get('value'));
				mm = b.getMonth()+1;
				var dd = b.getDate();
				if(dd<10){
					dd = "0"+dd;
				}
				var mon = getMonthByNumber(mm);
				if(mm<10){
					mm = "0"+mm;
				}
				var y = b.getFullYear();
				var start_date = dd + '-' + mon + '-' + y ;
				
			dojo.byId("lb_start_date").innerHTML = start_date;	
			
			var a = new Date(dijit.byId("end_date").get('value'));
				mm = a.getMonth()+1;
				var dd = a.getDate();
				if(dd<10){
					dd = "0"+dd;
				}
				var months = getMonthByNumber(mm);
				if(mm<10){
					mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = dd + '-' +months + '-' + y ;
				
			dojo.byId("lb_epx_date").innerHTML = epx_date;
/*			
			payment_method=dijit.byId('payment_method').get('value');
			temp='<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-10px;font-weight:bold;" id="table">'
			if(payment_method==1){
				temp+='<tr style="font-size:10px;border:1px solid #000;height:10px; ">';
				  temp+='<td width="25%" align="left" style="font-size:11px;"><div class="hidelabel showlabel" style="font-size:15px;"><?php if (!empty($this->branch_info['branch_namekh'])){ echo $this->branch_info['branch_namekh'];}?></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>';
				  temp+='<td width="50%" align="center" class="hidelabel showlabel"><img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br ></td>';
				  temp+='<td width="25%" class="hidelabel showlabel" align="center" style="font-size:14px;">'+label+'<br /><div style="font-size:17px;color:red;margin-top:-5px;">N<sup>o</sup> : '+new_receipt_no+'</td>';
				temp+='</tr></table>';
				temp+='<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-20px;font-weight:bold;" >'
					temp+='<tr style="font-size:10px;border:1px solid #000;height:10px; ">';
					  temp+='<td width="40%"><div class="hidelabel showlabel" ><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>';
					  temp+='<td width="20%" align="center" style="font-size:16px;"><div class="hidelabel showlabel" >បង្កាន់ដៃទទួលប្រាក់ RECEIPT</div></td>';
					  temp+='<td width="40%"><div class="hidelabel showlabel" ><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>';
					temp+='</tr></table>';
			}else{
				temp+='<tr style="font-size:10px;border:1px solid #000;height:10px; ">';
				  temp+='<td width="25%" align="left" style="font-size:11px;"><div class=" showlabel" style="font-size:15px;"><?php if (!empty($this->branch_info['branch_namekh'])){ echo $this->branch_info['branch_namekh'];}?></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>';
				  temp+='<td width="50%" align="center" class=" showlabel"><img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br ></td>';
				  temp+='<td width="25%" class=" showlabel" align="center" style="font-size:14px;">'+label+'<br /><div style="margin-top:-5px;color:red;font-size:17px;">N<sup>o</sup> : '+new_receipt_no+'</td>';
				temp+='</tr></table>';
				temp+='<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-20px;font-weight:bold;" >'	
					temp+='<tr style="font-size:10px;border:1px solid #000;height:10px; ">';
					  temp+='<td width="40%"><div class=" showlabel" ><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></div></td>';
					  temp+='<td width="20%" align="center" style="font-size:16px;"><div class=" showlabel" >បង្កាន់ដៃទទួលប្រាក់ RECEIPT</div></td>';
					  temp+='<td width="40%"><div class=" showlabel" ><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></div></td>';
					temp+='</tr>';
				temp+='</table>';
			}
*/			
			payment_method=dijit.byId('payment_method').get('value');
			getHeaderReceipt(payment_method,"<?php echo $this->branch_info['branch_namekh']?>",label,new_receipt_no);
			
			//dojo.byId('header_receipt').innerHTML = temp;
			dijit.byId("terms").show();	
		}
	}
	var url_getheaderreceipt = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-header-receipt')); ?>';
	function getHeaderReceipt(payment_method,branch_name,receipt_type,receipt_number){
		
		dojo.xhrPost({
			url:url_getheaderreceipt,
			content:{
				'payment_method':payment_method,
				'branch_name':branch_name,
				'receipt_type':receipt_type,
				'receipt_number':receipt_number,
			},
			handleAs:"json",
			load: function(data) {
				if(data){
					dojo.byId('header_receipt').innerHTML = data;
				}
			},
			error: function(err) {
			}
		});
	}
	
	function readMoneyInKhmer(netTotal){
		var str = netTotal.toString();
		str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
		if(first_decimal>0){string='ក្បៀស';}else{string="";str_cent=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
		first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
		last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
		money_khmer=read_money_in_khmer(netTotal);

		if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
		first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
		last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
		money_english=read_money_in_english(netTotal);
		read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'
		read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
		dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់');
	}
	
	function getMonthByNumber(m){
		var monthName=[
			 "01",
			 "02",
			 "03",
			 "04",
			 "05",
			 "06",
			 "07",
			 "08",
			 "09",
			 "10",
			 "11",
			 "12",
			];
		return (monthName[m-1]);
	}
	
	//save daata when sub button print 
	function printSubmit(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
		$('#office_receipt').submit();
		dijit.byId("terms").hide();	//hideDialog();
	}
	function hideDialog(){
		dijit.byId('terms').hide();
	}
	function getNewReceiptNo(){
		
	}
</script>
<div class="dijitHidden" style="width: 25cm !important; height: 13cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:26cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		<style>
			.data2{font-size:10px !important;}
			.showlabel{opacity:100 !important;}
		</style>
		<div id="divPrint" style="width: 25cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -18px;text-align:center;}
				.data{font-size:12.5px;font-weight:bold;}
				.data1{font-size:12px;font-weight:bold;}
				
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				.hidelabel{opacity:0;}
			</style>	
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
				<tr>
				    <td colspan="12"  align="center" style="">
						<div id="header_receipt"></div>
				    </td>
				</tr>
				<tr>
					<td width="5%"></td>
					<td width="6%"></td>
					<td width="5%"></td>
					<td width="7%"></td>
					<td width="5%"></td>
					<td width="5%"></td>
					<td width="6%"></td>
					<td width="6%"></td>
					<td width="3%"></td>
					<td width="3%"></td>
					<td width="24.5%"></td>
					<td width="24.5%"></td>
				</tr>
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap;font-size:12px;line-height:20px;">
							<tr>
								<td width="15%">ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
								<td width="20%">
									&nbsp;:&nbsp;<label id="lb_kh_name"  class="data" ></label>
									<div class="underline">&nbsp;.........................................</div>
								</td>
								<td width="11%" align="center"> អក្សរឡាតាំង/Latin</td>
								<td width="19%">
									&nbsp;:&nbsp;<label id="lb_en_name" class="data" ></label>
									<div class="underline">&nbsp;.......................................</div>
								</td>
								<td width="5%" align="center">ភេទ/Sex</td>
								<td width="7%">
									&nbsp;:&nbsp;<label id="lb_sex" class="data" ></label>
									<div class="underline">&nbsp;........</div>
								</td>
								
								<td width="13%">ថ្ងៃកំណើត/Date Of Birth</td>
								<td width="10%">
									&nbsp;:&nbsp;<label id="lb_dob" class="data" ></label>
									<div class="underline">...................</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="12">
						<table width="100%" border="0" style="white-space:nowrap;font-size:12px;line-height:20px;">
							<tr>
								<td width="7%" align="left">អត្តលេខ/ID</td>
								<td width="8%">
									&nbsp;:&nbsp;<label id="lb_stu_id" class="data" ></label>
									<div class="underline">..................</div>
								</td>
								<td width="8%" align="center">កម្រិត/Level</td>
								<td width="13%">
									&nbsp;:&nbsp;<label id="lb_grade" class="data" ></label>
									<div class="underline">..............................</div>
								</td>
								<td width="7%" align="center">បន្ទប់/Room</td>
								<td width="8%">
									&nbsp;:&nbsp;<label id="lb_room" class="data" ></label>
									<div class="underline">............</div>
								</td>
								<td width="9%" align="center">ម៉ោងសិក្សា/Time</td>
								<td width="13%">
									&nbsp;:&nbsp;<label id="lb_hour" class="data" ></label>
									<div class="underline">...............................</div>
								</td>
								<td width="13%">ប្រភេទសិស្ស/Stu.Type</td>
								<td width="14%">
									&nbsp;:&nbsp;<label id="lb_stu_type" class="data" ></label>
									<div class="underline">................................</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="12">
						<table width="100%" border="0" style="white-space:nowrap;font-size:12px;line-height:20px;margin-bottom:3px;">
							<tr>
								<td width="15%">លេខទូរសព្ទ/Phone Number</td>
								<td width="35%" align="left">
									&nbsp;:&nbsp; <label id="lb_phone" class="data" ></label>
									<div class="underline" style="text-align: left;">&nbsp;....................................................................................</div>
								</td>
								<td width="8%" align="center">សម្គាល់/Note</td>
								<td width="42%" align="left">
									&nbsp;:&nbsp; <label id="lb_note" class="data" ></label>
									<div class="underline" style="text-align: left;">&nbsp;......................................................................................................</div>     
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="12" style="border:1px solid #000;">
						<table width="100%" border="0" class="data2" style="white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
							<tr>
								<td width="8%"></td>
								<td width="3%"></td>
								<td width="4%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="6%"></td>
								<td width="10%"></td>
								<td width="6%"></td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;ថ្លៃសិក្សាពេញម៉ោង/Full Time Study Fee</td>
								<td>
									: <label id="lb_study_fee" class="data1" ></label>
									<div class="underline">.................</div>
								</td>
								<td >បញ្ចុះថ្លៃ/Discount</td>
								<td>
									: <label id="lb_discount" class="data1" ></label>
									<div class="underline">................</div>
								</td>
								<td >ថ្លៃសិក្សានៅសល់/Amount</td>
								<td>
									: <label id="lb_total_payment" class="data1" ></label>
									<div class="underline">................</div>
								</td>
								<td >ថ្លៃរដ្ឋបាល/Admin Fee</td>
								<td>
									: <label id="lb_admin_fee" class="data1" ></label>
									<div class="underline">.............</div>
								</td>
								<td >ថ្លៃសម្ភារៈ/Material Fee</td>
								<td>
									: <label id="lb_total_product_fee" class="data1" ></label>
									<div class="underline">..............</div>
								</td>
							</tr>
							<tr>
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="15%">ទឹកប្រាក់សរុប/Total Amount : </td>
											<td width="15%" align="center">
												<label id="lb_grand_total" class="data1" ></label>
												<div class="underline">.......................................</div>
											</td>
											<td width="12%" align="center">ទឹកប្រាក់ជំពាក់/Credit : </td>
											<td width="15%" align="center">
												<label id="lb_total_balance" class="data1" > </label>
												<div class="underline">........................................</div>
											</td>
											<td width="25%">ទឹកប្រាក់ទទួលបានសរុប/Total Received Amount</td>
											<td width="18%" style="border:1px solid #000;" align="center">
												<label id="lb_total_paid" class="data1" > </label>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%">ទឹកប្រាក់ទទួលបានជាអក្សរ/In Words : </td>
											<td width="82%" align="center">
												&nbsp;<label id="lb_read_money" class="data1" ></label>
												<div class="underline">.......................................................................................................................................................................................................................</div>  
											</td>
										</tr>
									</table>
								</td>	
							</tr>
							<tr>
								<td colspan="12">
									<table  width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%">មានសុពលភាពរយៈពេល/Payment Period : </td>
											<td width="21%" align="center">
												<label id="lb_payment_term" class="data1" ></label>
												<div class="underline">...................................................</div>
											</td>
											<td width="10%">ចាប់ពីថ្ងៃទី/Start Date : </td>
											<td width="21%" align="center">
												<label id="lb_start_date" class="data1" ></label>
												<div class="underline">...................................................</div>
											</td>
											<td width="9%">ដល់ថ្ងៃទី/End Date : </td>
											<td width="21%" align="center">
												<label id="lb_epx_date" class="data1" ></label>
												<div class="underline">.......................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr>
								<td width="70%">&nbsp;</td>
								<td width="30%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol;font-weight:bold;margin-top:-7px;">
							<tr>
								<td width="25%" align="center">ប្រធានគណនេយ្យ/Accounting Manager</td>
								<td width="25%" align="center">អ្នកបង់ប្រាក់/Payer</td>
								<td width="25%" align="center">បេឡា/Cashier</td>
								<td width="25%" align="center">អ្នកផ្តល់ព័ត៌មាន​/Receiptionist</td>
							</tr>
							<tr>
								<td colspan="4" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="4" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td align="center" style="font-size:12px;"></td>
								<td align="center"></td>
								<td align="center">
									<div style=" font-size: 12px;margin-top:-7px;"> 
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</div>
								</td>
								<td align="center"></td>
							</tr>
							<tr>
								<td colspan="4" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>	
				<tr>
					<td colspan="12" valign="top"  >
						<table width="100%" style="margin-top:-25px; font-family:Khmer OS Battambang, Times New Roman; font-size:10px;white-space:nowrap;line-height: 15px;">
							<tr>
								<td colspan="2" valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
							</tr>
							<tr>
								<td width="70%" valign="top" >
									<table width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang,Times New Roman;line-height: 13px;margin-top:-5px;">
										<tr>
											<?php 
												$footer ="";
												if (!empty($this->data['note_student_register_fulltime'])){
													$footer = explode(",", $this->data['note_student_register_fulltime']);
												}
											?>
											<td colspan="1" style="white-space: nowrap;">
												<?php if (!empty($footer)) foreach ($footer as $label){?>
													<?php echo $label;?> <br />
												<?php }?>
											</td>
										</tr>
									</table>
								</td>
								<td width="30%" valign="top" align="center"> 
								<?php 
									$phone ="";
									if (!empty($this->branch_info['branch_tel'])){
										$phone = explode(",", $this->branch_info['branch_tel']);
									}
								?>
									លេខទូរសព្ទ/Tel: ការិយាល័យផ្តល់ព័ត៌មាន/Information office <br />
									<div style=" width: 50%; text-align: left;">
									<?php if (!empty($phone)) foreach ($phone as $ss){?>
										- <?php echo $ss;?> <br />
									<?php }?>
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
			showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" showLabel="true" iconClass="dijitEditorIcon dijitEditorIconPrint"
			 type="button" onclick="printSubmit();">Print</button>
	</div>
</div>