<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_STUDENT_TEST'));
//print_r($this->session);
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/Textarea"]);
 </script>
<form id='frm_teststudent' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				dijit.byId('savenew').set('disabled',true);
				return true;
			}else {
				return false;
			}
	</script>
	
	<table cellspacing="10" class='fullside' >
		<tr>
			<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('EDIT_STUDENT_TEST')?></strong></legend>
						<table cellspacing="10"  width="100%">
							<tr>
								<td valign="top" width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
											<td><?php echo $tr->translate("NAME_KH")?></td>
											<td><input value="<?php echo $this->rs['kh_name']?>" type="text" name="kh_name" id="kh_name" required="1" class="fullside" dojoType="dijit.form.ValidationTextBox"   />
												<input value="<?php echo $this->rs['id']?>" type="hidden" name="id" id="id" dojoType="dijit.form.ValidationTextBox" />
											</td>
										</tr>
										<tr>
											<td style="white-space: nowrap;"><?php echo $tr->translate("NAME_EN")?></td>
											<td><input value="<?php echo $this->rs['en_name']?>" type="text" name="en_name" id="en_name" required="1"  class="fullside" dojoType="dijit.form.ValidationTextBox" /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("SEX")?></td>
											<td>
												<select name="sex" id="sex" class="fullside" dojoType="dijit.form.FilteringSelect"  >
													<option value="1" <?php if($this->rs['sex']==1){echo 'selected="selected"';}?>><?php echo $tr->translate('MALE')?></option>
													<option value="2" <?php if($this->rs['sex']==2){echo 'selected="selected"';}?>><?php echo $tr->translate('FEMALE')?></option>
												</select>
											</td>						
										</tr>
										<tr>
											<td><?php echo $tr->translate("DOB")?></td>
											<td><input type="text" value="<?php echo $this->rs['dob']?>" name="dob" id="dob" class="fullside"  value="now" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox"   /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("PHONE")?></td>
											<td><input value="<?php echo $this->rs['phone']?>" type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("ADDRESS")?></td>
											<td><textarea style="height:50px;font-family:'Khmer OS Battambang';font-size: 15px;" class="fullside" name="address" id="address" dojoType="dijit.form.Textarea" ><?php echo $this->rs['address']?></textarea></td>
										</tr>
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
										    <td><?php echo $tr->translate("RECEIPT")?></td>
											<td><input readonly type="text" name="receipt" id="receipt" class="fullside" dojoType="dijit.form.TextBox"  value="<?php echo $this->rs['receipt']?>"/></td>
										</tr>
										<!-- 
										<tr>
										    <td><?php //echo $tr->translate("SERIAL")?></td>
											<td><input type="text" value="<?php //echo $this->rs['serial']?>" name="serial" id="serial" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										 -->
										<tr>
										    <td><?php echo $tr->translate("DEGREE")?></td>
											<td>
												<select name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getDegreeType();"  >
													<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
														<option value="<?php echo $rs['id'];?>" <?php if($this->rs['degree']==$rs['id']){echo"selected";}?>><?php echo $rs['name'];?></option>
													<?php }}?>
												</select>
												<input type="hidden" dojoType="dijit.form.TextBox" name="degree_type" id="degree_type"/>
											</td>
										</tr>
										<!-- 
										<tr>
											<td><?php //echo $tr->translate("OLD_SCHOOL")?></td>
											<td><input type="text" value="<?php //echo $this->rs['old_school']?>" name="old_school" id="old_school" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
											 <td><?php //echo $tr->translate("OLD_GRADE")?></td>
											 <td><input type="text" value="<?php //echo $this->rs['old_grade']?>" name="old_grade" id="old_grade" class="fullside" dojoType="dijit.form.TextBox" /></td>
										</tr>
										 -->
										<tr>
											 <td><?php echo $tr->translate("PRICE")?></td>
											 <td><input onkeyup="readMoneyInKhmer();" value="<?php echo $this->rs['total_price']?>" type="text" readonly name="test_cost" required="1"  id="test_cost" class="fullside" dojoType="dijit.form.NumberTextBox"   /></td>
										</tr>
										<tr>
											<td></td>
											<td><input type="text" class="fullside" name="readmoney" id="readmoney" readonly dojoType="dijit.form.TextBox" /></td>
										</tr>
										<tr>	
											<td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
											<td>
												<select name="payment_method" id="payment_method" dojoType="dijit.form.FilteringSelect" class="fullside" required="true" autoComplete="false" queryExpr="*${0}*" onchange="getReceiptNo();">
												    <?php  if(!empty($this->payment_option))foreach($this->payment_option as $rs){?>
												    	<option value="<?php echo $rs['id'];?>" <?php if($this->rs['payment_method']==$rs['id']){echo"selected";}?> ><?php echo $rs['name'];?></option>
												    <?php }?>
												</select>
											</td>
										</tr>
										<tr>	
											<td><?php echo $tr->translate("PAYIMENT_NOTE");?></td>
											<td>
												<textarea dojoType="dijit.form.Textarea" style="min-height:40px;font-family:Khmer os Battambang" class="fullside" id="note_payment" name="note_payment"><?php echo $this->rs['payment_note'];?></textarea>
											</td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("STATUS")?></td>
											<td>
												<select type="text" name="status" id="status"  class="fullside" dojoType="dijit.form.FilteringSelect" >
													<option value="1" <?php if($this->rs['status']==1){echo"selected";}?>><?php echo $tr->translate('ACTIVE')?></option>
													<option value="0" <?php if($this->rs['status']==0){echo"selected";}?>><?php echo $tr->translate('DEACTIVE')?></option>								
												</select>
											</td>
										</tr>
										
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="0"  width="100%">
										<tr>
											<td valign="top"><?php echo $tr->translate("NOTE")?></td>
											<td><textarea style="height:100px !important;font-family:'Khmer OS Battambang';font-size: 15px;"  class="fullside" name="note" id="note" dojoType="dijit.form.Textarea" ><?php echo $this->rs['note']?></textarea></td>
										</tr>
										
										<tr>
											<td colspan="2">
												<fieldset> 
													<legend align="center" ><strong><?php echo $tr->translate("RESULT");?></strong></legend>
														<table width="100%">
															<tr>
																<td>
																	<tr>
																		<td><?php echo $tr->translate("DEGREE")?></td>
																		<td>
																			<select name="degree_result" id="degree_result" readonly class="fullside" dojoType="dijit.form.FilteringSelect"  >
																				<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
																					<option value="<?php echo $rs['id'];?>" <?php if($this->rs['degree']==$rs['id']){echo"selected";}?>><?php echo $rs['name'];?></option>
																				<?php }}?>
																			</select>
																		</td>
																	</tr>
																	<tr>
																		<td><?php echo $tr->translate("GRADE")?></td>
																		<td>
																			<input id="grade_result" />
																		</td>
																	</tr>
																	<tr>
																		<td><?php echo $tr->translate("SESSION")?></td>
																		<td>
																			<select name="session_result" id="session_result" class="fullside" dojoType="dijit.form.FilteringSelect"  >
																				<?php if(!empty($this->session)){foreach($this->session as $session){?>
																						<option value="<?php echo $session['id'];?>" <?php if($session['id']==$this->rs['session_result']){echo"selected";}?>><?php echo $session['name'];?></option>
																				<?php }}?>
																			</select>
																		</td>
																	</tr>
																</td>
															</tr>
														</table>
												</fieldset>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
				</fieldset>
			</td>
		</tr>		
		<tr>
			<td align="center">
				<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
					 iconClass="dijitIconClear"/>
				<input label="<?php echo $tr->translate("GO_EDIT")?>" onclick="submitData();" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  type="submit" iconClass="dijitIconNewTask"/>
				<input label="<?php echo $tr->translate("PRINT")?>" name='print' id='print' value='print' dojoType="dijit.form.Button" onclick="printReceipt();" type="button" iconClass="dijitIconNewTask"/>
			</td>
		</tr>	
	</table>
</form>


<?php /*/ receipt for data only ?>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:25cm; height: 16cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'" id="terms" >
		
		<style>
			.showlabel{opacity:100 !important;}
			.border{border:1px solid #000;}
			.defaultMargin{margin-top :0px !important;}
		</style>
		
		<div id="PrintReceipt" style="width: 25cm !important; height: 10cm ; padding: 0px; ">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
						text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -17px;text-align:left;}
				
				.data{font-size:13px;font-weight:bold;}
				.data1{font-size:12px;font-weight:bold;}
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				.hidelabel{opacity:0;}
			</style>
			
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 23px;margin-top: -3px;">
				<tr>
				    <td  align="center" style="">
						<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-20px;font-weight:bold;">
							<tr>
								<td width="25%" align="left" style="font-size:11px;">
									<div class="hidelabel showlabel" style="font-size:15px;"><?php if(!empty($this->branch_info['branch_namekh'])){ echo $this->branch_info['branch_namekh'];}?></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
								</td>
								<td width="50%" align="center" class="hidelabel showlabel">
									<img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
								</td>
								<td width="25%" align="center" style="font-size:17px;color:red;" class="hidelabel showlabel"><label id="lb_receipt_type" style="color:#000;font-size:14px;"> </label><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
							</tr>
						</table>
				    </td>
				</tr>
				<tr >
					<td >
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -25px;">
							<tr class="hidelabel showlabel">
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
								<td width="20%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td  valign="top">
						<table width="100%" style="font-family:Khmer OS Battambang, Times New Roman; font-size:12px;white-space:nowrap;line-height: 18px;margin-top:0px;">
							<tr>
								<td width="15%"></td>
								<td width="20%"></td>
								<td width="15%"></td>
								<td width="20%"></td>
								<td width="5%"></td>
								<td width="5%"></td>
								<td width="5%"></td>
								<td width="15%"></td>
							</tr>
							<tr>
								<td class="hidelabel showlabel">ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
								<td align="center">
									 <label id="lb_studentkh" class="data"></label>
									<div class="underline hidelabel showlabel">...............................................</div>
								</td>
								<td align="center" class="hidelabel showlabel"> អក្សរឡាតាំង/Latin</td>
								<td align="center">
									 <label id="lb_studenten" class="data"></label>
									<div class="underline hidelabel showlabel">..............................................</div>
								</td>
								<td align="center" class="hidelabel showlabel">ភេទ/Sex</td>
								<td align="center">
									 <label id="lb_gender" class="data"></label>
									<div class="underline hidelabel showlabel">.............</div>
								</td>
								
								<td align="center" class="hidelabel showlabel">&nbsp;ថ្ងៃកំណើត/Date of Birth</td>
								<td align="center">
									 <label id="lb_dob" class="data"></label>
									<div class="underline hidelabel showlabel">...................</div>
								</td>
							</tr>
								
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang', Times New Roman;line-height: 18px;">
										<tr>
											<td width="7%" class="hidelabel showlabel">ឤសយដ្ឋាន/Address</td>
											<td width="93%" align="center">
												 <label id="lb_address" class="data"></label>
												<div class="underline hidelabel showlabel">............................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang', Times New Roman;line-height: 18px;">
										<tr>
											<td width="10%" class="hidelabel showlabel">លេខទូរសព្ទ/Phone Number</td>
											<td width="90%" align="center">
												 <label id="lb_phone" class="data"></label>
												<div class="underline hidelabel showlabel">..................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 20px;">
										<tr align="center">
											<td>&nbsp;</td>
											<td width="40%"><label id="fulltime_eng"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/checked.png'?>"></label> តេស្តកម្រិតអង់គ្លេសពេញម៉ោង Full-Time English Test</td>
											<td width="40%"><label id="parttime_eng"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/uncheck.png'?>"></label> តេស្តកម្រិតអង់គ្លេសក្រៅម៉ោង Part-Time English Test</td>
											<td width="20%"><label id="other_opt"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/uncheck.png'?>"></label> តេស្តផ្សេងៗ Other Test</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" class="border">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 18px;padding:5px;margin-top:2px;">
										<tr>
											<td width="20%"></td>
											<td width="30%"></td>
											<td width="30%"></td>
											<td width="20%"></td>
										</tr>
										<tr>
											<td colspan="4">
												<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang', Times New Roman;line-height: 18px;">
													<tr align="center">
														<td width="10%" class="hidelabel showlabel">ថ្លៃតេស្ដ/ Test Fee</td>
														<td width="40%">
															 <label id="lb_price"  class="data"></label>
															<div class="underline hidelabel showlabel">...............................................................................................</div>
														</td>
																	
														<td width="25%" class="hidelabel showlabel">&nbsp;ទឹកប្រាក់ទទួលបានសរុប/Total Received Amount</td>
														<td width="25%">
															 <label id="lb_total_amount"  class="data"></label>
															<div class="underline hidelabel showlabel">................................................</div>
														</td>
													</tr>
												</table>
											</td>
										</tr>	
											
										<tr align="center">
											<td class="hidelabel showlabel">&nbsp;ទឹកប្រាក់ទទួលបានជាអក្សរ/In Words</td>
											<td colspan="3">
												 <label id="lb_total_inword"  class="data"></label>
												<div class="underline hidelabel showlabel">..............................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" class="border" style="padding-bottom: 17px;">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 18px;padding:5px;">
										<tr>
											<td width="9%"></td>
											<td width="15%"></td>
											<td width="9%"></td>
											<td width="15%"></td>
											<td width="10%"></td>
											<td width="15%"></td>
											<td width="12%"></td>
											<td width="15%"></td>
										</tr>
										<tr>
											<td colspan="8" align="center" class="hidelabel showlabel">លទ្ធផលតេស្ដ/ Result Test</td>
										</tr>
										<tr>
											<td class="hidelabel showlabel">&nbsp;កម្រិត/Level</td>
											<td>
												 <label id="lb_degree"  class="data"></label>
												<div class="underline hidelabel showlabel">....................................</div>
											</td>
											<td class="hidelabel showlabel">&nbsp;បន្ទប់/Room</td>
											<td>
												 <label id="lb_room"  class="data"></label>
												<div class="underline hidelabel showlabel">....................................</div>
											</td>
											<td class="hidelabel showlabel">&nbsp;ម៉ោងសិក្សា/Time</td>
											<td >
												 <label id="lb_time_study"  class="data">&nbsp;</label>
												<div class="underline hidelabel showlabel">.....................................</div>
											</td>
											<td class="hidelabel showlabel">&nbsp;ឈ្មោះគ្រូ/Teacher's name</td>
											<td >
												 <label id="lb_teachername"  class="data">&nbsp;</label>
												<div class="underline hidelabel showlabel">............................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" align="right">
									<table width="30%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';margin-top:0px; ">
										<tr>
											<td width="70%">&nbsp;</td>
											<td width="30%"align="right" ><span class="hidelabel showlabel">រាជធានីភ្នំពេញ.ថ្ងៃទី </span>&nbsp;<?php echo date('d');?> <span class="hidelabel showlabel">/</span> &nbsp;<?php echo date('m');?> <span class="hidelabel showlabel">/</span> &nbsp;<?php echo date('Y');?></td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -7px;">
										<tr class="hidelabel showlabel" style="font-family:Khmer OS Muol,'Arial Black';">
											<td align="center" width="25%">ប្រធានគណនេយ្យ/Accounting Manager</td>
											<td align="center" width="25%">អ្នកបង់ប្រាក់/Payer</td>
											<td align="center" width="25%">បេឡា/Cashier</td>
											<td align="center" width="25%">អ្នកផ្ដល់ព័ត៌មាន/Receptionist</td>
										</tr>
										<tr>
											<td colspan="4">&nbsp;</td>
										</tr>
										
										<tr>
											<td align="center" >&nbsp;</td>
											<td align="center" >&nbsp;</td>
											<td align="center" >&nbsp;
												<div style=" font-size: 12px;margin-top:15px;"> 
													<?php 
													   $session_user=new Zend_Session_Namespace('auth');
													   $last_name=$session_user->last_name;
													   $username = $session_user->first_name;
													   echo $last_name." ".$username; 
													?>
												</div>
											</td>
											<td align="center" >&nbsp;</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr class="hidelabel showlabel">
								<td colspan="8" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td valign="top" >
						<table width="100%" style="margin-top:-25px; font-family:Khmer OS Battambang, Times New Roman; font-size:10px;white-space:nowrap;line-height: 15px;">
							<tr class="hidelabel showlabel">
								<td colspan="2" valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
							</tr>
							
							<tr>
								<td width="70%" valign="top" >
									<table class="defaultMargin" width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang,Times New Roman;line-height: 13px;margin-top:-30px;">
										<tr class="hidelabel showlabel">
											<td colspan="2" style="white-space: pre;"><?php if (!empty($this->data['note_receipt_studenttest'])){echo $this->data['note_receipt_studenttest'];}?></td>
										</tr>
									</table>
								</td>
								<td width="30%" valign="top" align="center"> 
								<?php 
									$phone ="";
									if (!empty($this->branch_info['branch_tel'])){
										$phone = explode(",", $this->branch_info['branch_tel']);
									}
								?>
									<span class="hidelabel showlabel">លេខទូរសព្ទ/Tel: ការិយាល័យផ្តល់ព័ត៌មាន/Information office </span><br />
									<div style=" width: 50%; text-align: left;margin-top:-8px;line-height:12px;">
									<?php if (!empty($phone)) foreach ($phone as $ss){?>
										<?php echo "- ".$ss;?> <br />
									<?php }?>
									</div>
								</td>
								
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<div>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="printSubmit();"><?php echo $tr->translate("SAVE_PRINT");?></button>
		
		</div>
	</div>
</div>

<?php */?>
<?php // receipt fulldata ?>

<div class="dijitHidden" style="padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:28cm; height: 16cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'" id="terms" >
		
		<style>
			.showlabel{opacity:100 !important;}
		</style>
		<div id="PrintReceipt" style="width: 20cm !important; height: 10cm ; padding: 0px; ">
			<table border="0" width="100%" class="print" cellspacing="0" cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 23px;">
				<tr>
				    <td  align="center" >
						<div id="header_receipt"></div>
				    </td>
				</tr>
				
				<tr>
					<td  valign="top">
						<table width="100%" style="font-family:Khmer OS Battambang, Times New Roman; font-size:12px;white-space:nowrap;line-height: 18px;margin-top:-10px;">
							<style>
								.fontbig{
									font-size: 15px;	
								}
								.fonttel{
									font-size: 18px;	
								}
								.pleft{
									width: 110px;	
								}
								.label{ font-weight: bold;font-size: 22px;}
								.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
										margin-top: -25px; line-height: 25px;
									    text-align: center;
										}
								.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
										line-height: 25px;}
								.h{ margin-top: -8px;/*margin-left:4px;*/}
				​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
							   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
							   .khmer{font:12px 'Khmer OS Battambang';}
							   .one{white-space:nowrap;}
							   
								.underline{margin-top: -18px; text-align: center;}
								.data{font-size:13px;font-weight:bold;}
								.data1{font-size:12px;font-weight:bold;}
								.receiptno{font-size:15px;font-weight:bold;}
								.tab_row{ margin-top: -8px;}
								.fonteng{font-size:12px;}
								.hidelabel{opacity:0;}
							</style>
							<tr>
								<td width="15%"></td>
								<td width="20%"></td>
								<td width="15%"></td>
								<td width="20%"></td>
								<td width="5%"></td>
								<td width="5%"></td>
								<td width="5%"></td>
								<td width="15%"></td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap;font-size:12px;line-height:20px;">
										<tr>
											<td width="15%">ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
											<td width="20%">
												&nbsp;:&nbsp;<label id="lb_studentkh"  class="data" ></label>
												<div class="underline">&nbsp;.........................................</div>
											</td>
											<td width="11%" align="center"> អក្សរឡាតាំង/Latin</td>
											<td width="19%">
												&nbsp;:&nbsp;<label id="lb_studenten" class="data" ></label>
												<div class="underline">&nbsp;.......................................</div>
											</td>
											<td width="5%" align="center">ភេទ/Sex</td>
											<td width="7%">
												&nbsp;:&nbsp;<label id="lb_gender" class="data" ></label>
												<div class="underline">&nbsp;........</div>
											</td>
											
											<td width="13%">ថ្ងៃកំណើត/Date Of Birth</td>
											<td width="10%">
												&nbsp;:&nbsp;<label id="lb_dob" class="data" ></label>
												<div class="underline">...................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td>&nbsp;ឤសយដ្ឋាន/Address</td>
								<td colspan="7" align="center">
									&nbsp;<label id="lb_address" class="data"></label>
									<div class="underline">: ..........................................................................................................................................................................................................</div>
								</td>
							</tr>
							<tr>
								<td>&nbsp;លេខទូរសព្ទ/Phone Number</td>
								<td colspan="7" align="center">
									&nbsp;<label id="lb_phone" class="data"></label>
									<div class="underline">: ..........................................................................................................................................................................................................</div>
								</td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
										<tr>
											<td width="35%" align="center"><label id="fulltime_eng"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/checked.png'?>"></label> តេស្តកម្រិតអង់គ្លេសពេញម៉ោង Full-Time English Test</td>
											<td width="35%" align="center"><label id="parttime_eng"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/uncheck.png'?>"></label> តេស្តកម្រិតអង់គ្លេសក្រៅម៉ោង Part-Time English Test</td>
											<td width="30%" align="center"><label id="other_opt"><img style="width: 15px;height:15px;margin-bottom:-3px;" src="<?php echo $this->baseUrl().'/images/uncheck.png'?>"></label> តេស្តផ្សេងៗ Other Test</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" style="border:1px solid #000;">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 18px;margin-bottom: 5px;">
										<tr>
											<td width="20%"></td>
											<td width="30%"></td>
											<td width="30%"></td>
											<td width="20%"></td>
										</tr>
										<tr>
											<td>&nbsp;ថ្លៃតេស្ដ/ Test Fee</td>
											<td align="center">
												&nbsp;<label id="lb_price"  class="data"></label>
												<div class="underline">: ....................................................................</div>
											</td>
											<td>&nbsp;ទឹកប្រាក់ទទួលបានសរុប/Total Received Amount</td>
											<td align="center">
												&nbsp;<label id="lb_total_amount"  class="data"></label>
												<div class="underline">: ..............................................</div>
											</td>
										</tr>
										<tr>
											<td>&nbsp;ទឹកប្រាក់ទទួលបានជាអក្សរ/In Words</td>
											<td colspan="3" align="center">
												&nbsp;<label id="lb_total_inword"  class="data"></label>
												<div class="underline">: ....................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" style="border:1px solid #000;padding-bottom: 5px;">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 18px;">
										<tr>
											<td width="10%"></td>
											<td width="20%"></td>
											<td width="10%"></td>
											<td width="10%"></td>
											<td width="10%"></td>
											<td width="10%"></td>
											<td width="10%"></td>
											<td width="20%"></td>
										</tr>
										<tr>
											<td colspan="8" align="center">លទ្ធផលតេស្ដ/ Result Test</td>
										</tr>
										<tr>
											<td>&nbsp;កម្រិត/Level</td>
											<td>
												&nbsp;<label id="lb_degree"  class="data"></label>
												<div class="underline">: ..........................................</div>
											</td>
											<td>&nbsp;បន្ទប់/Room</td>
											<td>
												&nbsp;<label id="lb_room"  class="data"></label>
												<div class="underline">: .............................</div>
											</td>
											<td>&nbsp;ម៉ោងសិក្សា/Time</td>
											<td >
												&nbsp;<label id="lb_time_study"  class="data">&nbsp;</label>
												<div class="underline">: ....................</div>
											</td>
											<td>&nbsp;ឈ្មោះគ្រូ/Teacher's name</td>
											<td >
												&nbsp;<label id="lb_teachername"  class="data">&nbsp;</label>
												<div class="underline">: .....................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" align="right">
									<table width="30%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
										<tr>
											<td width="70%">&nbsp;</td>
											<td width="30%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 20px;margin-top:-10px;">
										<tr style="font-family:Khmer OS Muol,'Arial Black';">
											<td align="center" width="25%">ប្រធានគណនេយ្យ/Accounting Manager</td>
											<td align="center" width="25%">អ្នកបង់ប្រាក់/Payer</td>
											<td align="center" width="25%">បេឡា/Cashier</td>
											<td align="center" width="25%">អ្នកផ្ដល់ព័ត៌មាន/Receptionist</td>
										</tr>
										<tr>
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr>
											<td align="center" >&nbsp;</td>
											<td align="center" >&nbsp;</td>
											<td align="center" >
												<div style="margin-top:10px;">
													<?php 
													   $session_user=new Zend_Session_Namespace('auth');
													   $last_name=$session_user->last_name;
													   $username = $session_user->first_name;
													   echo "".$last_name." ".$username;
													?>
												</div>
											</td>
											<td align="center" >&nbsp;</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="8" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td valign="top" >
						<table width="100%" style="margin-top:-25px; font-family:Khmer OS Battambang, Times New Roman; font-size:10px;white-space:nowrap;line-height: 15px;">
							<tr>
								<td colspan="2" valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
							</tr>
							
							<tr>
								<td width="70%" valign="top" >
									<table width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang,Times New Roman;line-height: 14px;margin-top: -5px;">
										<tr>
											
											<?php 
												$footer ="";
												if (!empty($this->data['note_receipt_studenttest'])){
													$footer = explode(",", $this->data['note_receipt_studenttest']);
												}
											?>
										
											<td colspan="1" style="white-space: nowrap;">
												<?php if (!empty($footer)) foreach ($footer as $label){?>
													<?php echo $label;?> <br />
												<?php }?>
											</td>
										</tr>
									</table>
								</td>
								<td width="30%" valign="top" align="center"> 
								<?php 
									$phone ="";
									if (!empty($this->branch_info['branch_tel'])){
										$phone = explode(",", $this->branch_info['branch_tel']);
									}
								?>
									លេខទូរសព្ទ/Tel: ការិយាល័យផ្តល់ព័ត៌មាន/Information office <br />
									<div style=" width: 50%; text-align: left;">
									<?php if (!empty($phone)) foreach ($phone as $ss){?>
										- <?php echo $ss;?> <br />
									<?php }?>
									</div>
								</td>
								
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<div>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="printSubmit();"><?php echo $tr->translate("SAVE_PRINT");?></button>
		
		</div>
	</div>
</div>
<?php //*/?>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->dept));?> );
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: grade_store,
			autoComplete: true,                        
			required: false,
			id: "grade_result",
			name: "grade_result",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE")?>",          
			onChange: function() {  
			}
		}, "grade_result");
		
		getAllGrade();
		readMoneyInKhmer();
		getDegreeType();
	});
	


// printReceipt for data only

function printReceipt(){
	if(dijit.byId('frm_teststudent').validate()) {
		
		new_receipt_no = dijit.byId("receipt").get('value');

		label = "Student Test";
		
		readMoneyInKhmer();
		getDegreeType();
		checked =  "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		uncheck = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		var degree_type = dijit.byId('degree_type').get('value');
		
		if(degree_type==1){
			dojo.byId("fulltime_eng").innerHTML = uncheck;
			dojo.byId("parttime_eng").innerHTML = uncheck;
			dojo.byId("other_opt").innerHTML = checked;
		}else if(degree_type==2){
			dojo.byId("fulltime_eng").innerHTML = checked;
			dojo.byId("parttime_eng").innerHTML = uncheck;
			dojo.byId("other_opt").innerHTML = uncheck;
		}else if(degree_type==3){
			dojo.byId("fulltime_eng").innerHTML = uncheck;
			dojo.byId("parttime_eng").innerHTML = checked;
			dojo.byId("other_opt").innerHTML = uncheck;
		}
		
		dojo.byId("lb_studentkh").innerHTML = "&nbsp;"+dijit.byId("kh_name").get('value');
		dojo.byId("lb_studenten").innerHTML = "&nbsp;"+dijit.byId("en_name").get('value');
		//dojo.byId("lb_serial").innerHTML = dijit.byId("serial").get('value');
		//dojo.byId("lb_degree").innerHTML = dijit.byId("degree").attr('displayedValue');
		dojo.byId("lb_gender").innerHTML = "&nbsp;"+dijit.byId("sex").attr('displayedValue');
		dojo.byId("lb_price").innerHTML = "&nbsp;$ "+dijit.byId("test_cost").get('value').toFixed(2);
		dojo.byId("lb_total_amount").innerHTML = "&nbsp;$ "+dijit.byId("test_cost").get('value').toFixed(2);
		dojo.byId("lb_dob").innerHTML = "&nbsp;"+dijit.byId("dob").get('value');
		dojo.byId("lb_address").innerHTML = "&nbsp;"+dijit.byId("address").get('value');
		dojo.byId("lb_phone").innerHTML = "&nbsp;"+dijit.byId("phone").get('value');
		//dojo.byId("lb_note").innerHTML = dijit.byId("note").get('value');
		dojo.byId("lb_total_inword").innerHTML = dijit.byId('readmoney').get('value');
		var d = dijit.byId("dob").get('value');
		 if(d!=null){
			 var day = d.getDate();
			 var mon = d.toDateString().substr(4,3);
			 var year = d.getFullYear();
			 dojo.byId("lb_dob").innerHTML  = day+'/'+mon+'/'+year;
		 }else{
			 dojo.byId("lb_dob").innerHTML  = '';
		}
		payment_method=dijit.byId('payment_method').get('value');
		getHeaderReceipt(payment_method,"<?php echo $this->branch_info['branch_namekh']?>",label,new_receipt_no);
		dijit.byId("terms").show();	
	}
}
var url_getheaderreceipt = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-header-receipt')); ?>';
function getHeaderReceipt(payment_method,branch_name,receipt_type,receipt_number){
	
	dojo.xhrPost({
		url:url_getheaderreceipt,
		content:{
			'payment_method':payment_method,
			'branch_name':branch_name,
			'receipt_type':receipt_type,
			'receipt_number':receipt_number,
		},
		handleAs:"json",
		load: function(data) {
			if(data){
				dojo.byId('header_receipt').innerHTML = data;
			}
		},
		error: function(err) {
		}
	});
}
function getNewReceiptNo(){
		
}


/* printReceipt for full data

function printReceipt(){
	if(dijit.byId('frm_teststudent').validate()) {
		readMoneyInKhmer();
		getDegreeType();
		checked =  "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		uncheck = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		var degree_type = dijit.byId('degree_type').get('value');
		if(degree_type==1){
			dojo.byId("fulltime_eng").innerHTML = uncheck;
			dojo.byId("parttime_eng").innerHTML = uncheck;
			dojo.byId("other_opt").innerHTML = checked;
		}else if(degree_type==2){
			dojo.byId("fulltime_eng").innerHTML = checked;
			dojo.byId("parttime_eng").innerHTML = uncheck;
			dojo.byId("other_opt").innerHTML = uncheck;
		}else if(degree_type==3){
			dojo.byId("fulltime_eng").innerHTML = uncheck;
			dojo.byId("parttime_eng").innerHTML = checked;
			dojo.byId("other_opt").innerHTML = uncheck;
		}
	//dojo.byId("lb_receipt").innerHTML = dijit.byId("receipt").get('value');
		dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt").get('value');
	dojo.byId("lb_studentkh").innerHTML = "&nbsp;"+dijit.byId("kh_name").get('value');
	dojo.byId("lb_studenten").innerHTML = "&nbsp;"+dijit.byId("en_name").get('value');
   // dojo.byId("lb_serial").innerHTML = dijit.byId("serial").get('value');
	//dojo.byId("lb_degree").innerHTML = dijit.byId("degree").attr('displayedValue');
	dojo.byId("lb_gender").innerHTML = "&nbsp;"+dijit.byId("sex").attr('displayedValue');
	dojo.byId("lb_price").innerHTML = "&nbsp;$ "+dijit.byId("test_cost").get('value').toFixed(2);
	dojo.byId("lb_total_amount").innerHTML = "&nbsp;$ "+dijit.byId("test_cost").get('value').toFixed(2);
	dojo.byId("lb_dob").innerHTML = "&nbsp;"+dijit.byId("dob").get('value');
	dojo.byId("lb_address").innerHTML = "&nbsp;"+dijit.byId("address").get('value');
	dojo.byId("lb_phone").innerHTML = "&nbsp;"+dijit.byId("phone").get('value');
	//dojo.byId("lb_note").innerHTML = dijit.byId("note").get('value');
	dojo.byId("lb_total_inword").innerHTML = dijit.byId('readmoney').get('value');
	var d = dijit.byId("dob").get('value');
	 if(d!=null){
		 var day = d.getDate();
		 var mon = d.toDateString().substr(4,3);
		 var year = d.getFullYear();
		 dojo.byId("lb_dob").innerHTML  = day+'/'+mon+'/'+year;
	 }else{
		 dojo.byId("lb_dob").innerHTML  = '';
	}
	dijit.byId("terms").show();	
	}
}
*/

function readMoneyInKhmer(){
	netTotal = dijit.byId("test_cost").get('value').toFixed(2);
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	
	if(first_decimal>0){string='ដុល្លា និង ';last_string="សេន"}else{string="";str_cent="";last_string="ដុល្លាគត់";}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal);
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal);
	money_english=read_money_in_english(netTotal);
	
	//read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string;
	//read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )';
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string);
}
function submitData(){
	if(dijit.byId('frm_teststudent').validate()) {
		loadingBlock();
		dijit.byId('savenew').set('disabled',true);
		dijit.byId('frm_teststudent').submit();
	}
}
function printSubmit(){
	window.frames["print_frame"].document.body.innerHTML = dojo.byId('PrintReceipt').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    submitData();
}
function hideDialog(){
	dijit.byId('terms').hide();
}

var url_get_grade = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
function getAllGrade(){
	dept_id = dijit.byId('degree_result').get('value');
	if(dept_id==''){
		return false;
	}
	
	old_grade = '<?php echo $this->rs['grade_result']?>';
	
	dojo.xhrPost({
		url:url_get_grade,
		content:{
			'dept_id':dept_id
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_result').set('store',grade_store);  
			
			if(old_grade!=''){
				dijit.byId('grade_result').attr('value',old_grade);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getdegree = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'getdegreetype')); ?>';
function getDegreeType(){
	degree = dijit.byId('degree').get('value');
	dojo.xhrPost({
		url:url_getdegree,
		content:{
			'degree':degree
			},
		handleAs:"json",
		load: function(data) {
			
			if(data!=''){
				dijit.byId('degree_type').attr('value',data);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
 </script>