<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TRANSPORTATION_SERVICE')); 
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'transportation','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 50%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("TRANSPORTATION_SERVICE");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td><?php echo $tr->translate("STUDENT_NAME")?></td>
										<td>
											<input type="text" name="stu_name" id="stu_name" class="fullside" value="<?php echo $this->row['stu_khname']."-".$this->row['stu_enname'];?>" readonly dojoType="dijit.form.TextBox" />
										</td>
									</tr>
									
									<tr>
										<td><?php echo $tr->translate("STUDENT_CODE")?></td>
										<td>
											<input type="text" name="stu_code" id="stu_code" class="fullside" value="<?php echo $this->row['stu_code'];?>" dojoType="dijit.form.TextBox" />
										</td>
									</tr>
									
									<tr>
										<td><?php echo $tr->translate("SERVICE")?></td>
										<td>
											<select name="service" id="service" dojoType="dijit.form.FilteringSelect"  class="fullside" >
												<option value="-1">No Service</option>
												<?php if(!empty($this->transport_service)){foreach ($this->transport_service as $transport){?>
													<option value="<?php echo $transport['id']?>" <?php if($transport['id']==$this->row['service_id']){echo "selected='selected'";}?>><?php echo $transport['name']?></option>
												<?php }}?>
											</select>
										</td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CAR_ID")?></td>
										<td>
											<select name="car_id" id="car_id" dojoType="dijit.form.FilteringSelect" required="false"  class="fullside" >
												<option value="-1">No Car ID</option>
												<?php if(!empty($this->all_car)){foreach ($this->all_car as $all_car){?>
													<option value="<?php echo $all_car['id']?>" <?php if($all_car['id']==$this->row['car_id']){echo "selected='selected'";}?>><?php echo $all_car['name']?></option>
												<?php }}?>
											</select>
										</td>
									</tr>
									
									<?php 
										$time_for_car = $this->row['time_for_car'];
										$time_id = explode(',', $time_for_car);
									?>
									<tr>
										<td colspan="2" align="center">
											<table style="text-align:center;">
												<tr>
													<td><input <?php if(!empty($time_id)){foreach($time_id as $time){if($time==1){echo "checked";}}}?> type="checkBox" dojoType="dijit.form.CheckBox" value="07:30 am" id="time1" name="time1" onclick="getValue();" />07:30 am</td>
													<td><input <?php if(!empty($time_id)){foreach($time_id as $time){if($time==2){echo "checked";}}}?> type="checkBox" dojoType="dijit.form.CheckBox" value="10:30 am" id="time2" name="time2" onclick="getValue();" />10:30 am</td>
													<td><input <?php if(!empty($time_id)){foreach($time_id as $time){if($time==3){echo "checked";}}}?> type="checkBox" dojoType="dijit.form.CheckBox" value="01:30 pm" id="time3" name="time3" onclick="getValue();" />01:30 pm</td>
													<td><input <?php if(!empty($time_id)){foreach($time_id as $time){if($time==4){echo "checked";}}}?> type="checkBox" dojoType="dijit.form.CheckBox" value="04:30 pm" id="time4" name="time4" onclick="getValue();" />04:30 pm</td>
													<input type="hidden" id="time_identity" name="time_identity" value="<?php echo $this->row['time_for_car'];?>" />
												</tr>
											</table>
										</td>
									</tr>
									
									<tr>
										<td colspan="2" align="center">
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>

<script type="text/javascript">
	dojo.ready(function(){

	});

	function getValue(){
		i=0;
		$("#time_identity").val('');
		for(i=1;i<=4;i++){
			if(dijit.byId('time'+i).checked){
				//alert(dijit.byId('time'+i).get('value'));
				if($("#time_identity").val()!="") {
					var time_identity = $("#time_identity").val();
					$("#time_identity").val(time_identity+','+i);
				} else {$("#time_identity").val(i);}
			}
		}
	}

</script>