
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TRANSPORTATION_SERVICE')); 
	$frm =  $this->form_search;
?>

<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'transportation','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width:100%">
	  <tr> 
			<td> <?php echo $frm->getElement("title");?></td>
			<td> <?php echo $frm->getElement("branch");?></td>
			<td>
				<select name="service" id="service" dojoType="dijit.form.FilteringSelect" class="fullside" >
					<option value="0"> select service </option>
					<?php if(!empty($this->transport_service)){foreach ($this->transport_service as $transport){?>
						<option value="<?php echo $transport['id']?>" <?php if($transport['id']==$this->adv_search['service']){echo "selected='selected'";}?>><?php echo $transport['name']?></option>
					<?php }}?>
				</select>
			</td>
			<td>
				<select name="car" id="car" dojoType="dijit.form.FilteringSelect" class="fullside" >
					<option value="0"> select car </option>
					<?php if(!empty($this->all_car)){foreach ($this->all_car as $car){?>
						<option value="<?php echo $car['id']?>" <?php if($car['id']==$this->adv_search['car']){echo "selected='selected'";}?>><?php echo $car['name']?></option>
					<?php }}?>
				</select>
			</td>
			<td> <?php echo $frm->getElement("start_date");?></td>
	   	  	<td> <?php echo $frm->getElement("end_date");?></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
	  </tr>
	 </table>
</form>


<?php echo $this->list;?>