<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('KHMER_FULLTIME_PAYMENT_PAYABLE_REPORT')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<?php
	$array_month = array(
			"1"=>"មករា",
			"2"=>"កុម្ភៈ",
			"3"=>"មីនា",
			"4"=>"មេសា",
			"5"=>"ឧសភា",
			"6"=>"មិថុនា",
			"7"=>"កក្កដា",
			"8"=>"សីហា",
			"9"=>"កញ្ញា",
			"10"=>"តុលា",
			"11"=>"វិច្ឆិកា",
			"12"=>"ធ្នូ",
			
			"01"=>"មករា",
			"02"=>"កុម្ភៈ",
			"03"=>"មីនា",
			"04"=>"មេសា",
			"05"=>"ឧសភា",
			"06"=>"មិថុនា",
			"07"=>"កក្កដា",
			"08"=>"សីហា",
			"09"=>"កញ្ញា",
			"10"=>"តុលា",
			"11"=>"វិច្ឆិកា",
			"12"=>"ធ្នូ",
	);
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-payable-nextmonth-kh-fulltime')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" class="fullside" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement("branch");?>
			</td>
			<td>
				<?php echo $frm->getElement("degree_kh_ft");?>
			</td>
			<td>
				<?php echo $frm->getElement("grade_kh_ft");?>
			</td>
			<td>
	    		<select name="for_month" id="for_month" dojoType="dijit.form.FilteringSelect" class="fullside" >
	    			<option value="0"> select month </option>
	    			<?php if(!empty($this->all_month)){foreach ($this->all_month as $month){?>
	    				<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->search['for_month']){echo "selected='selected'";}?>> <?php echo $month['name']?> </option>
	    			<?php }}?>
	    		</select>
	    	</td>
	    	<td>
	    		<select name="for_year" id="for_year" dojoType="dijit.form.FilteringSelect" class="fullside" >
	    			<?php for($i=2016;$i<=date("Y")+1;$i++){?>
	    				<option value="<?php echo $i;?>" <?php if($i==$this->search['for_year']){echo "selected='selected'";}?>> <?php echo $i;?> </option>
	    			<?php }?>
	    		</select>
	    	</td>
			
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
		<style>
			table{
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
		</style>
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold; color:#000; font-size: 16px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("KHMER_FULLTIME_PAYMENT_PAYABLE_REPORT")?></strong><br />
						<?php if(!empty($this->search['for_month'])){echo "សំរាប់ខែ ".$array_month[$this->search['for_month']]." ".$this->search['for_year'];}?>
					</td>
					<td width="20%" align="right">
						<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name'];}?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:13px; height: 20px;border: 1px solid #000;background: #ccc;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate("N_O")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("RECEIPT_NO")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_ID")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_NAME")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("SEX")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PHONE")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("GRADE")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("START_DATE")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("VALIDATE")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("DISCOUNT")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("TOTAL_PAYMENT")?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("NOTE")?></td>
							</tr>
						<?php $i=0;$totalpaid=0;$totalbalance=0;$name=""; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
									$name = $row['stu_khname'];
									if($name==""){
										$name = $row['stu_enname'];
									}		
									$discount="";
									if($row['discount_percent']>0 && $row['discount_fix']>0){
										$discount = $row['discount_percent']."%+$".$row['discount_fix'];
									}else if($row['discount_percent']>0){
										$discount = $row['discount_percent']."%";
									}else if($row['discount_fix']>0){
										$discount = "$".$row['discount_fix'];
									}
							?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['receipt'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $name;?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['tel'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['grade'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</td>
								<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $discount;?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo "$ ".$row['grand_total_payment'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['note'];?></td>
 							</tr>
							<?php }}?>	 
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>			
	</div>		
</div>





