<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm =  $this->form_search;
?>	
<title><?php echo $tr->translate('RENTAL_NEARLY_END_CONTRACT_RPT');?></title>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-cus-nearly-end-service')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">
	    <tr>
	   	<td><?php echo $frm->getElement("title");?> </td>
		<td><?php echo $frm->getElement("branch");?> </td>
		<td><?php echo $frm->getElement("cus_name");?> </td>
		<td><?php echo $frm->getElement("end_date");?> </td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button> </td>
		</tr>
		
	</table>
</form>	
</div>
<style>
.hover:hover{background: #ddd;}
</style>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
	 <style>
				table { page-break-inside:auto;font-family:'Times New Roman','Khmer OS Battambang'; }
                tr{ page-break-inside:avoid; page-break-after:auto }
			   #header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
		</style>
		<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;font-family:'Times New Roman','Khmer OS Battambang';">
			<tr>
				<td width="15%" align="center">
					<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
				</td>
				<td align="center" width="70%">
					<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("របាយការណ៍អតិថិជនជិតដល់ថ្ងៃបង់ថ្លៃជួលតូប"); ?></strong><br />
					<span style="font-weight: bold;font-size: 12px; font-family:'Times New Roman','Khmer OS Battambang';​">&nbsp;<?php echo $tr->translate("DATE"); ?>&nbsp; <?php echo date("d-m-Y",strtotime($this->search['end_date']));?></span><br />
				</td>
				<td width="15%" >
					&nbsp;
				</td>
				
			</tr>
			
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;font-family:'Times New Roman','Khmer OS Battambang';"  border="1" >
						<thead>
						<tr style="font-size:12px; height: 20px;border: 1px solid #000; background: #ccc; line-height: 30px; font-weight: bold;" align="center" >
							<td>&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("CUS_ID"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("CUS_NAME"); ?>&nbsp;</td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate("SEX"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("PHONE"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("ADDRESS"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("START_DATE"); ?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("END_DATE"); ?>&nbsp;</td>
							<td style="border: 1px solid #000;"><?php echo $tr->translate("USER"); ?></td>
							<td style="border: 1px solid #000;"><?php echo $tr->translate("STATUS"); ?></td>
							<td style="border: 1px solid #000;"><?php echo $tr->translate("EXPIRES_DATE"); ?></td>
						</tr>
						</thead>
						<?php $total=0;$stu_num=0;$old_id=0;?>
					<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->cus)){foreach ($this->cus AS $row) { $i++;
					
						$date1=date_create($row['end_date']);
						$date2=date_create($this->search['end_date']);
						$diff=date_diff($date1,$date2);
						$day=$diff->format("%R%a");
						 
						$name=$row['first_name'];
						if($name==""){
							$name = $row['last_name'];
						}
					?>
						<tr style="font-size:12px; height: 30px;border: 1px solid #000;font-family:'Times New Roman','Khmer OS Battambang';" align="center" class="hover" >
							<td style="border: 1px solid #000;"><?php echo $i;?></td>
							<td>&nbsp;<?php echo $row['customer_code'];?></td>
							<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['first_name'];?></td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo $row['c_sex'];?></td>
							<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['phone'];?></td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo $row['address'];?>&nbsp;</td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($row['start_date']));?></td>	
							<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($row['end_date']));?></td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
							<td style="border: 1px solid #000;">&nbsp;<?php echo $row['c_status'];?>&nbsp;</td>
							
							<?php if($day>=0){
								$daylate ="Late ".abs($day);
							}else{
								$daylate ="Remain ".abs($day);
							}?>
							<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;">&nbsp;<?php echo ($daylate);?> days</td>
 													</tr>
												<?php }}?>	 
					</table>	
					<br />
					<br />
					<?php echo $this->footerReport;?>
			
				</td>
			</tr>
			
		</table>
					
	</div>		
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>




