<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm =  $this->form_search;
	//print_r($this->rs[0]);
?>	
<title><?php echo $tr->translate('របាយការណ៍បិទបញ្ជីលុយខ្មែរ និង ដុល្លា');?></title>



<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">
	    <tr>
	    	<td><?php echo $frm->getElement('branch');?></td>
	    	<td>
			 	<?php echo $frm->getElement('shift');?>
			</td>
			<td><?php echo $frm->getElement('user');?></td>
			<td>
				<select name="type" id="type" class="fullside" dojoType="dijit.form.FilteringSelect"  >
					<option value="">select type</option>
					<option value="1" <?php if($this->search['type']==1){echo 'selected="selected"';}?>>ខ្មែរពេញម៉ោង</option>
					<option value="6" <?php if($this->search['type']==6){echo 'selected="selected"';}?>>Englist Fulltime</option>
					<option value="2" <?php if($this->search['type']==2){echo 'selected="selected"';}?>>Englist Parttime and Other</option>
					<option value="3" <?php if($this->search['type']==3){echo 'selected="selected"';}?>>Transportation</option>
					<option value="4" <?php if($this->search['type']==4){echo 'selected="selected"';}?>>Food and Stay</option>
					<option value="5" <?php if($this->search['type']==5){echo 'selected="selected"';}?>>Product</option>
					<option value="10" <?php if($this->search['type']==10){echo 'selected="selected"';}?>>សិស្សធ្វើតេស្ត</option>
					<option value="8" <?php if($this->search['type']==8){echo 'selected="selected"';}?>>ផ្ញើរកង់ ម៉ូតូ និង អេតចាយ</option>
					<option value="7" <?php if($this->search['type']==7){echo 'selected="selected"';}?>>ជួលតូប</option>
					<option value="9" <?php if($this->search['type']==9){echo 'selected="selected"';}?>>ចំណូលផ្សេងៗ</option>
					
				</select>
			</td>
		</tr>
		<tr>	
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><?php echo $frm->getElement('payment_method');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button> </td>
	    </tr>
	</table>
</form>	

<style>
.hover:hover{background: #ddd;}
tr.row_control {
    display: table-row !important;
}
</style>

<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<form  action="<?php echo $this->url(array('module'=>'allreport','controller'=>'submitdailyincome','action'=>'rpt-submit-daily-income')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div id="divPrint">
	<style>
		.bor{
			border-right: 1px solid #000;	
			border-bottom: 1px solid #000;
			font-size:13px;
		}
		.bor_r{
			border-right: 1px solid #000;	
			font-size:13px;
		}
		.padd{
			padding: 0 3px;	
		}
		#row{ font-size:12px; line-height: 20px;border: 1px solid #000;font-family:'Times New Roman','Khmer OS Battambang';  }
		
		table { 
			page-break-inside:auto;
			font-family:'Times New Roman','Khmer OS Battambang'; 
		}
		tr{ 
			page-break-inside:auto; 
			page-break-after:auto; 
		}
	</style>

	<?php 
		$shift = array(1=>"10:00am",2=>"03:00 pm",3=>"07:00 pm");
	?>

		<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;font-family:'Times New Roman','Khmer OS Battambang';">
			<tr>
				
				<td width="22%" align="center">
					<img style="width:50%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
				</td>
				<td align="center" width="56%" style="font-family: 'Times New Roman','Khmer OS Battambang';color:#000; font-size: 14px;">
					<strong  style="font-weight:bold;color:#000; font-size: 17px;font-family: 'Times New Roman','Khmer OS Battambang';​"><?php echo $tr->translate("របាយការណ៍បិទបញ្ជីលុយខ្មែរ និង ដុល្លា");?></strong><br />
					<strong style="font-family: 'Times New Roman','Khmer OS Battambang';color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong> <br />   
					<?php if($this->search['shift']>0){echo "Time : ".$shift[$this->search['shift']]." , "."Shift : ".($this->search['shift']-1);}?>
				</td>
				<td align="center" width="22%" style="white-space: nowrap;">
					<?php if(!empty($this->branch)){echo "Branch : ".$this->branch."</br>";}?>
				</td>
				
			</tr>
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="8"​ style=" border: solid 1px #000; margin:0 auto; width:100%; border-collapse: collapse; white-space: nowrap;font-family:'Khmer OS Battambang';"  border="1" >
	 					 <thead>
		 					 <tr align="center" style="background: #c1d0f3;font-size: 13px; line-height: 20px;font-weight: bold;">
								<td class="padd">N<sup>o</sup></td>
								<td class="padd">Branch</td>
								<td class="padd">Type</td>
								<td class="padd">For Date</td>
								<td class="padd">Shift</td>
								<td class="padd">User</td>
								<td class="padd">Payment Method</td>
								<td class="padd">Total Amount</td>
								<td class="padd">Amount in Dollars</td>
								<td class="padd">Amount in Riels</td>
								
								<td class="padd">Edit</td>
		 					 </tr>
	 					 </thead>
	 					 <?php $i=0; $grand_total = 0;$grand_total_in_dollar=0;$grand_total_in_riel=0;$shift="";$payfor_type=""; if (!empty($this->row)) foreach ($this->row as $rs){ $i++;?>
	 					 
	 					 <?php 
	 					 	if($rs['shift'] == 1){
	 					 		$shift = "វេនទី ".$rs['shift']."( 10:30am )";
	 					 	}else if($rs['shift'] == 2){
	 					 		$shift = "វេនទី ".($rs['shift']-1)." ( 03:00pm )";
	 					 	}else if($rs['shift'] == 3){
	 					 		$shift = "វេនទី ".($rs['shift']-1)." ( 07:00pm )";
	 					 	}
	 					 	
	 					 	if($rs['payfor_type'] == 1 ){
	 					 		$payfor_type = "ខ្មែរពេញម៉ោង";
	 					 	}else if($rs['payfor_type'] == 2 ){
	 					 		$payfor_type = "Englist Parttime and Other";
	 					 	}else if($rs['payfor_type'] == 3 ){
	 					 		$payfor_type = "Transportation";
	 					 	}else if($rs['payfor_type'] == 4 ){
	 					 		$payfor_type = "Food and Stay";
	 					 	}else if($rs['payfor_type'] == 5 ){
	 					 		$payfor_type = "Product";
	 					 	}else if($rs['payfor_type'] == 6 ){
	 					 		$payfor_type = "Englist Fulltime";
	 					 	}else if($rs['payfor_type'] == 7 ){
	 					 		$payfor_type = "ជួលតូប";
	 					 	}else if($rs['payfor_type'] == 8 ){
	 					 		$payfor_type = "ផ្ញើរកង់ ម៉ូតូ និង អេតចាយ";
	 					 	}else if($rs['payfor_type'] == 9 ){
	 					 		$payfor_type = "ចំណូលផ្សេងៗ";
	 					 	}else if($rs['payfor_type'] == 10 ){
	 					 		$payfor_type = "សិស្សធ្វើតេស្ត";
	 					 	}
	 					 	
	 					 	
	 					 ?>
	 					 
	 					 <tr id="row" align="center" class="hover">
	 					 	<td class="padd">&nbsp;<?php echo $i;?>&nbsp;</td>
	 					 	<td class="padd">&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $payfor_type;?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo date("d-m-Y",strtotime($rs['for_date']));?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $shift;?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $rs['user_name'];?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $rs['payment_method'];?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo "$ ".number_format($rs['total_amount'],2);?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo "$ ".number_format($rs['amount_usd'],2);?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo number_format($rs['amount_riel'],2)." ៛";?>&nbsp;</td>
							<td style="min-width: 50px;" class="padd">&nbsp;<a href="<?php echo $this->baseUrl().'/allreport/accounting/editsubmit/id/'.$rs['id']?>" target="_blank">Edit</a>&nbsp;</td>
	 					 </tr>
	 					 <?php 
	 					 $grand_total = $grand_total + $rs['total_amount'];
	 					 $grand_total_in_dollar = $grand_total_in_dollar + $rs['amount_usd'];
	 					 $grand_total_in_riel = $grand_total_in_riel + $rs['amount_riel'];
					}
	 					 
	 					 ?>
	 					 <tr align="center" style="background: #e8e8e8;font-size: 16px;font-family: 'Times New Roman','Khmer OS Battambang';">
	 					 	<td colspan="7">Total</td>
	 					 	<td ><?php echo "$ ".number_format($grand_total,2);?></td>
	 					 	<td colspan="2"></td>
	 					 </tr>
	 					 <tr align="center" style="background: yellow;font-size: 18px;font-family: 'Times New Roman','Khmer OS Battambang';">
	 					 	<td colspan="7">Grand Total</td>
	 					 	<td style="border-left: 1px solid yellow;"></td>
	 					 	<td ><?php echo "$ ".number_format($grand_total_in_dollar,2);?></td>
	 					 	<td ><?php echo number_format($grand_total_in_riel,2)." ៛";?></td>
	 					 </tr>
	 				</table>
				</td>
			</tr>	
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">
					<?php echo $this->footerReport;?>						
				</td>
			</tr>
		</table>
	</div>
	</form>	
</div>
<script type="text/javascript">
</script>
 