<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_COURSESTUDY')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$gep_session=$this->row_gep;
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">   
  		 if(this.validate()) {
			branch_id = dijit.byId('branch').get('value');
			if(branch_id==-1 || branch_id==0){
		 		alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?> !!! ");
		 		dijit.byId("branch").focus();
		 		return false;
			}
			year = dijit.byId('study_year').get('value');
			if(year==-1 || year==0){
				alert("<?php echo $tr->translate("PLEASE_SELECT_ACADEMIC_YEAR")?> !!! ");
		 		dijit.byId("study_year").focus();
		 		return false;
			}
			loadingBlock();
			dijit.byId('save_close').set('disabled',true);
			return true;
   		}else {
			return false;
   		}
	</script>
	<table  cellspacing="10" style="margin: 0 auto; width: 100%;white-space:nowrap;">
		<tr>
			<td width="33%" valign="top">
				<fieldset>
				<legend align="center"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:0px 10px 10px 10px;" cellspacing="7" >
						<tr>
							<td><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select name="branch" id="branch" class="fullside" readOnly onchange="" dojoType="dijit.form.FilteringSelect" type="text" >
									<option value="-1"><?php echo $tr->translate("SELECT_BRANCH");?></option>
									<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
									<option value="<?php echo $branch['id'];?>" <?php if($this->row_gep['branch_id']==$branch['id']){echo "selected='selected'";}?>><?php echo $branch['name'];?></option>
									<?php }}?>
								</select>
								<input type="hidden" name="payment_id" id="payment_id" value="<?php echo $this->row_gep['id'];?>" dojoType="dijit.form.TextBox" >
							</td>
						</tr>
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("STUDENT_TYPE");?>
								  <?php echo $register->getElement('ids');?>
								  <?php echo $register->getElement('parent_id');?>
							</td>
							<td><?php echo $register->getElement('student_type');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<div id="student_ids">
									<select name="old_studens" id="old_studens" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_code)){foreach($this->old_stu_code as $stu_code){?>
											<option value="<?php echo $stu_code['stu_id']?>"><?php echo $stu_code['stu_code']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="student_id"><?php echo $register->getElement('stu_id');?></div>
								<div id="drop_stu_code"><?php echo "";?></div>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="student_old_name">
									<select name="old_stu_name" id="old_stu_name" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<?php if(!empty($this->old_stu_name)){foreach($this->old_stu_name as $stu_name){?>
											<option value="<?php echo $stu_name['stu_id']?>"><?php echo $stu_name['name']?></option>
										<?php }}?>
									</select>
								</div>
								<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
								<div id="drop_stu_name"><?php echo "";?></div>
							</td>
						</tr>
						<tr>
							<td width="20%"><?php echo $tr->translate("NAME_EN");?></td>
							<td width="80%"><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input type="text"  class="fullside" name="dob" id="dob" value="<?php echo $this->row_gep['dob']?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							<td><input type="text"  class="fullside" name="address" id="address" value="<?php echo $this->row_gep['address']?>" dojoType="dijit.form.TextBox" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" id="phone" class="fullside" value="<?php echo $this->row_gep['tel']?>" dojoType="dijit.form.TextBox" /></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
				<legend align="center"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:0px 10px 10px 10px;" cellspacing="7" >
						<tr>
							<td width="20%"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td width="80%"><?php echo $register->getElement('study_year');?></td>
						</tr>
						<tr>
							<input type="hidden" name="old_stu_code" id="old_stu_code" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="old_degree" id="old_degree" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="old_grade" id="old_grade" dojoType="dijit.form.TextBox" />
						
							<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
							<td><input id="dept" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
							<td><input id="grade" /></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("ROOM_NAME");?></td>
							<td>
								<select class="fullside"  tabindex="24" name="room" id="room" onchange="" dojoType="dijit.form.FilteringSelect" required="false">
									<option value="-1" ><?php echo $tr->translate("SELECT_ROOM")?></option>
									<?php if(!empty($this->room)){foreach($this->room as $room){?>
										<option value="<?php echo $room['id']?>"<?php if($room['id']==$this->row_gep['room_id']){echo 'selected="selected"';}?> ><?php echo $room['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td title="ចាប់ពីម៉ោង"><?php echo $tr->translate("SESSION");?>*</td>
							<td>
								<select class="fullside"  tabindex="24" name="session" id="session" onchange="" dojoType="dijit.form.FilteringSelect" required="false">
									<option value='1' <?php if($this->row_gep['session']==1){echo "selected";}?>><?php echo $tr->translate('MORNING')?></option>
									<option value='2' <?php if($this->row_gep['session']==2){echo "selected";}?>><?php echo $tr->translate('AFTERNOON')?></option>
									<option value='3' <?php if($this->row_gep['session']==3){echo "selected";}?>><?php echo $tr->translate('EVERNING')?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("TIME");?></td>
							<td>
							    <select dojoType="dijit.form.FilteringSelect" class="fullside" id="study_time" name="study_time" required="false">
									<option value="select time">select time</option>
									<?php if(!empty($this->all_time)){foreach($this->all_time as $time){?>
										<option value="<?php echo $time['name']?>" <?php if($time['name'] == $this->row_gep['time']){echo "selected='selected'";}?>><?php echo $time['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><?php echo $register->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><?php echo $register->getElement('end_date');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("NOTE");?></td>
							<td><?php echo $register->getElement('not');?></td>	
						</tr>
						<tr>	
							<td colspan="2"><?php echo $this->row_gep['create_date'];?></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
				<legend align="center"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:0px 10px 10px 10px;" cellspacing="7" >
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td width="80%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('payment_term');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('tuitionfee');?></td>
						</tr>
						
						<input type="hidden" name="price_per_section" id="price_per_section" dojoType="dijit.form.TextBox" >
						<tr>
							<td>
								<div id="label_amount">
									<?php echo $tr->translate("AMOUNT");?>
								</div>
							</td>
							<td>
								<div id="amount_section">
									<input name="amount_section" id="amount_section" onkeyup="calculateTotalFee();netTotal();" dojoType="dijit.form.TextBox" value="<?php echo $this->row_gep['qty']?>" class="fullside" type="text"/>
								</div>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DISCOUNT");?></td>
							<td>
								<table width="100%" style="white-space: nowrap;">
									<tr>
										<td width="10%">(%)&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount');?></td>
										<td width="10%">&nbsp;&nbsp;($)&nbsp;&nbsp;</td>
										<td width="40%"><?php echo $register->getElement('discount_fix');?></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
							<td title='Ex: 20 or 10%'><?php echo $register->getElement('total');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
							<td><?php echo $register->getElement('books');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("BALANCE");?></td>
							<td><?php echo $register->getElement('remaining');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("CREATE_DATE");?></td>
							<td><?php echo $register->getElement('create_date');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("វេន");?></td>
							<td>
								<select name="shift" id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="1" <?php if($this->row_gep['shift']==1){echo "selected='selected'";}?>>វេនទី1</option>
									<option value="2" <?php if($this->row_gep['shift']==2){echo "selected='selected'";}?>>វេនទី2</option>
									<option value="3" <?php if($this->row_gep['shift']==3){echo "selected='selected'";}?>>វេនទី3</option>
								</select>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("is start");?></td>
							<td>
								<input name="is_start" id="is_start" dojoType="dijit.form.TextBox" value="<?php echo $this->row_gep['is_start'];?>" class="fullside" />
							</td>
						</tr>
					</table>	
				</fieldset>		
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="center">
				<input type="checkbox" value="1" name="is_void" id="is_void" <?php if($this->row_gep['is_void']==1){echo 'onclick="return false;"';}?> dojoType="dijit.form.CheckBox"  /> Void
			</td>
		</tr>
		
		<tr>
			<div id="addrow" >
				<td colspan="3">
					<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
							<tr id="head-title" class="head-td" align="right"></tr>
					</table>
				</td>
			</div>
		</tr>
		<tr>
			<td colspan="1">
				<input type="hidden" class="fullside" name="readmoney" id="readmoney" readonly dojoType="dijit.form.TextBox" />
			</td>
			<td colspan="2" align="right">
				<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
					<tr>
						<td ><?php echo $tr->translate("EXCHANGE_RATE")." (៛)";?></td>
						<td align="right">
							<input type="text" name="ex_rate" id="ex_rate" readonly value="<?php echo $this->row_gep['exchange_rate'] ;?>" dojoType="dijit.form.NumberTextBox" />
						</td>
					</tr>
					<tr>
						<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
						<td align="right"><input type="text" readonly="readonly" value="<?php echo $this->row_gep['grand_total_payment'] ;?>" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
						<td align="right"><input  type="text" readonly="readonly" value="<?php echo $this->row_gep['grand_total_payment_in_riel'] ;?>" name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
						<td align="right"><input  type="text" readonly="readonly" value="<?php echo $this->row_gep['grand_total_paid_amount'] ;?>" name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo $this->row_gep['grand_total_balance'] ;?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
				</table>
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="center">
				<input type="submit" name="save_close" id="save_close" value="រក្សាទុក &ចាកចេញ" label="<?php echo $tr->translate("GO_EDIT");?>"  dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconSave" />
			</td>
		</tr>
		
		
	</table>	
</form>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require('dojox.form.BusyButton');
	
	dojo.require("dojo.NodeList-manipulate");
	
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );

	dojo.ready(function(){
	
		changControll();
		
		new dijit.form.FilteringSelect({
			store: dept_store,
			autoComplete: true,                        
			required: false,
			id: "dept",
			name: "dept",           
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_DEGREE")?>",          
			onChange: function() {  
				dept_id = dijit.byId('dept').get('value');
				dijit.byId('grade').attr('value','');
				getallModel(dept_id); 
				//getStudentNo(dept_id);
			}
		}, "dept");
		
		new dijit.form.FilteringSelect({
			//store: dept_store,
			autoComplete: true,  
			required: false,			
			id: "grade",
			name: "grade",           
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE")?>",          
			onChange: function() {  
				//make_id = dijit.byId('grade').get('value');
				//paymentTerm();
			}
		}, "grade");
		dijit.byId('dept').attr('value','<?php echo $this->row_gep['degree']?>');
		 
		 
		setReadonlyPageEdit(); 
		 
	});	

	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-grade')); ?>';
	function getallModel(dept_id){
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade').set('store',grade_store);  
				dijit.byId('grade').attr('value','<?php echo $this->row_gep['grade']?>'); 

			},
			error: function(err) {
				//alert(err);
			}
		});
	}

	function paymentTerm(){
		old_grade='<?php echo $this->row_gep['grade'];?>';
    	old_payterm='<?php echo $this->row_gep['payment_term'];?>';
    	grade=dijit.byId('grade').get('value');
    	payterm=dijit.byId('payment_term').get('value');
    	if(old_grade==grade && old_payterm==payterm){
    		defaultPayment();
	    }else{
			study_year=dijit.byId('study_year').get('value');
			payment_term=dijit.byId('payment_term').get('value');
			levele=dijit.byId('grade').get('value');
			if(study_year!='' && payment_term !='' && levele !='' ){
				getPaymentTerms(study_year,levele,payment_term);
			} 
			dijit.byId('discount').attr('value','0');
	    	dijit.byId('books').attr('value','0');
	    	dijit.byId('remaining').attr('value','0');
	    	dijit.byId('remark').attr('value','0');
	    	//dijit.byId('char_price').attr('value','0');
	    	dijit.byId('not').attr('value',''); 
	    }
	}
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-payment-gep')); ?>';
	function getPaymentTerms(study_year,levele,payment_term){
		dijit.byId('tuitionfee').attr('value',0);
    	dijit.byId('total').attr('value',0);
    	dijit.byId('books').attr('value',0);
    	dijit.byId('discount').attr('value',0);
    	dijit.byId('remaining').attr('value',0);
    	dijit.byId('remark').attr('value',0);
		dojo.xhrPost({
			url:url_getpaymentterm,
			content:{
				'study_year':study_year,
				'levele':levele,
				'payment_term':payment_term,
				},
			handleAs:"json",
			load: function(data) {
				  if(data){
					dijit.byId('tuitionfee').attr('value',data.tuition_fee);
					dijit.byId('total').attr('value',data.tuition_fee);
					//dijit.byId('discount').attr('value','0');
					dijit.byId('books').attr('value',data.tuition_fee);
					dijit.byId('price_per_section').attr('value',data.tuition_fee);
				  }else {
					 dijit.byId('tuitionfee').attr('value','0'); 
					 dijit.byId('total').attr('value','0'); 
					 dijit.byId('discount').attr('value','0');
					 dijit.byId('books').attr('value','0');
					 dijit.byId('remaining').attr('value','0');
					 dijit.byId('remark').attr('value','0');
					// dijit.byId('char_price').attr('value','0');
				  }
			},
			error: function(err) {
				//alert(err);
			}
		});
	}
	function defaultPayment(){
		dijit.byId('tuitionfee').attr('value','<?php echo $this->row_gep['tuition_fee'];?>');
    	dijit.byId('total').attr('value','<?php echo $this->row_gep['total_payment'];?>');
    	dijit.byId('discount').attr('value','<?php echo $this->row_gep['discount_percent'];?>');
    	dijit.byId('books').attr('value','<?php echo $this->row_gep['paid_amount'];?>');
    	dijit.byId('remaining').attr('value','<?php echo $this->row_gep['balance_due'];?>');
    	dijit.byId('remark').attr('value','<?php echo $this->row_gep['other_fee'];?>');
    	dijit.byId('not').attr('value','<?php echo $this->row_gep['note'];?>');
    	dijit.byId('session').attr('value','<?php echo $this->row_gep['session'];?>');
    	dijit.byId('amount_section').attr('value','<?php echo $this->row_gep['qty'];?>');
    	dijit.byId('price_per_section').attr('value','<?php echo $this->row_gep['price_per_sec'];?>');
		netTotal();
	}
	//set value totale 
	function getTotale(){
		tuitionfee = dijit.byId('tuitionfee').get('value');
		amount_section = dijit.byId('amount_section').get('value');
		tuitionfee = tuitionfee * amount_section;
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		
		discount=dijit.byId('discount').get('value');
		discount = isNaN(discount)?0:discount;

		discount_fix=dijit.byId('discount_fix').get('value');
		discount_fix = isNaN(discount_fix)?0:discount_fix;

		pc=discount/100;
		ds=(tuitionfee-discount_fix)*pc;
		old_totale=(tuitionfee-discount_fix) - ds;
		//alert('hello');
		
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		
		totals=parseFloat(old_totale)+parseFloat(remark);
		
		dijit.byId('total').attr('value',totals.toFixed(2));
		dijit.byId('books').attr('value',totals.toFixed(2));
		getRemaining();netTotal();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
	}
	function getDisccount(){
		tuitionfee=dijit.byId('tuitionfee').get('value');
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			   dijit.byId('total').attr('value',totale.toFixed(2));
			//   dijit.byId('remaining').attr('value','0');
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
				//getTotale();
			  //  dijit.byId('remaining').attr('value','0');
			}
	}
	//calculator date by select term_payment
	function getDateTerm(type) {
		// alert(1);
		if(type==1){
			payment_term=dijit.byId('payment_term').get('value');
			start_date=dijit.byId('start_date').get('value');
			
			amount_section = dijit.byId('amount_section').get('value');
			
			var a = new Date(start_date);
			
			if(payment_term==1){
				 mm = a.getMonth()+(1)+1;
				 var dd = a.getDate();
				 if(dd<10){
				   dd = "0"+dd;
				 }
				 if(mm<10){
				   mm = "0"+mm;
				 }
				 var y = a.getFullYear();
				 var epx_date = y + '-' + mm + '-' + dd ;
				 dijit.byId('end_date').attr('value',epx_date);
			 }
			 else if(payment_term==2){
				 mm = a.getMonth()+(3)+1;
				 var dd = a.getDate();
				 if(dd<10){
				   dd = "0"+dd;
				 }
				 if(mm<10){
				   mm = "0"+mm;
				 }
				 var y = a.getFullYear();
				 var epx_date = y + '-' + mm + '-' + dd ;
				 dijit.byId('end_date').attr('value',epx_date);
			 }
			 else if(payment_term==3){
				 mm = a.getMonth()+(6)+1;
				 var dd = a.getDate();
				 if(dd<10){
				   dd = "0"+dd;
				 }
				 if(mm<10){
				   mm = "0"+mm;
				 }
				 var y = a.getFullYear();
				 var epx_date = y + '-' + mm + '-' + dd ;
				 dijit.byId('end_date').attr('value',epx_date);
			 }
			 else if(payment_term==4){
				 mm = a.getMonth()+(12)+1;
				 var dd = a.getDate();
				 if(dd<10){
				   dd = "0"+dd;
				 }
				 if(mm<10){
				   mm = "0"+mm;
				 }
				 var y = a.getFullYear();
				 var epx_date = y + '-' + mm + '-' + dd ;
				 dijit.byId('end_date').attr('value',epx_date);
			 }else if(payment_term==5){
				 var amount_day = dijit.byId('amount_section').get('value');;
				 var start_date = dijit.byId('start_date').get('value');
				 var year = start_date.getFullYear();
				 var month = start_date.getMonth();
				 var date = start_date.getDate();
				 for(var i=0; i<amount_day; i++){
					  var epx_date = new Date(year, month, date + i);
				 }
				 dijit.byId('end_date').attr('value',epx_date); 
			 }	
		}else{
			/*
			payment_term = dijit.byId('payment_term').get('value');
			if(payment_term == 5){
				start_date = dijit.byId('start_date').get('value');
				end_date = dijit.byId('end_date').get('value');
				//alert(start_date+" , "+end_date)
				
				//day = end_date - start_date;
				
				var timeDiff = (end_date.getTime() - start_date.getTime());
				if(timeDiff>=0){
					var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1 ; // +1 because they also count the first day that register
					dijit.byId('amount_section').attr('value',diffDays);
				}else{
					dijit.byId('amount_section').attr('value',0);
				}
				calculateTotalFee();netTotal();
			}
			*/
		}
	}
	
	function setReadonlyPageEdit(){
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("old_stu_name").set('readOnly',true);
		dijit.byId("old_studens").set('readOnly',true);
		dijit.byId("en_name").set('readOnly',true);
		dijit.byId("kh_name").set('readOnly',true);
		dijit.byId("sex").set('readOnly',true);
		dijit.byId("dob").set('readOnly',true);
		dijit.byId("phone").set('readOnly',true);
		dijit.byId("address").set('readOnly',true);
		//dijit.byId("study_year").set('readOnly',true);
		//dijit.byId("room").set('readOnly',true);
		//dijit.byId("dept").set('readOnly',true);
		//dijit.byId("grade").set('readOnly',true);
		
		//dijit.byId("session").set('readOnly',true);
		//dijit.byId("study_time").set('readOnly',true);
		
		
		
		dijit.byId("readmoney").set('readOnly',true);
		
		
		<?php if($this->user_type>2){//1=admin , 2=account manager ?>
			dijit.byId("reciept_no").set('readOnly',true);
			dijit.byId("create_date").set('readOnly',true);
			dijit.byId("start_date").set('readOnly',true);
			dijit.byId("end_date").set('readOnly',true);
			
			dijit.byId("tuitionfee").set('readOnly',true);
			dijit.byId("payment_term").set('readOnly',true);
			dijit.byId("amount_section").set('readOnly',true);
			dijit.byId("discount").set('readOnly',true);
			dijit.byId("discount_fix").set('readOnly',true);
			dijit.byId("remark").set('readOnly',true);
			
			dijit.byId("books").set('readOnly',true);
			dijit.byId("not").set('readOnly',true);
			dijit.byId("remaining").set('readOnly',true);
		<?php }?>
	}
	
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	function netTotal() {
		var netTotal=0;
		var netPaidAmount=0;
		
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		readMoneyInKhmer(grand_total_paid.toFixed(2));
	}


	function readMoneyInKhmer(netTotal){
		//alert(netTotal);
		var str = netTotal.toString();
		str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
		if(first_decimal>0){string='និង';}else{string="";str_cent=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
		first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
		last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
		money_khmer=read_money_in_khmer(netTotal);

		if(first_decimal>0){string_en='និង';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
		first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
		last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
		money_english=read_money_in_english(netTotal);
		read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'

		read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
		
		dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់');
	}

	function displayAmountSection(){
		// payment_term = dijit.byId('payment_term').get('value');
		// if(payment_term==5){
			// document.getElementById('amount_section').style.display="block";
			// document.getElementById('label_amount').style.display="block";
			
		// }else{
			// document.getElementById('amount_section').style.display="none";
			// document.getElementById('label_amount').style.display="none";
			// //alert(222);
		// }
	}

	function calculateTotalFee(){
		getDisccount();getTotale();
	}

	function setStudyTime(){
		/*
		session = dijit.byId('session').get('value');
		if(session==1){
			dijit.byId('study_time').attr('value','8:00AM - 10:30AM ');
		}else if(session==2){
			dijit.byId('study_time').attr('value','2:00PM - 4:30PM ');
		}else if(session==3){
			dijit.byId('study_time').attr('value','5:30PM - 6:30PM ');
		}else{
			dijit.byId('study_time').attr('value','');
		}
		*/
	}

	function changControll(){
		document.getElementById('student_ids').style.display="block";
		document.getElementById('student_old_name').style.display="block";
		document.getElementById('student_id').style.display="none";
		document.getElementById('name_stu').style.display="none";
		document.getElementById('drop_stu_code').style.display="none";
		document.getElementById('drop_stu_name').style.display="none";
	}
	///get price balance where complete=0
	function getPriceBalance(){
		student_type=dijit.byId('student_type').get('value');
		old_studens=dijit.byId('old_studens').get('value');
		if(student_type==3){
			if(old_studens != -1){
				getBalancePrice(2,old_studens);
			}
		}
	}
	//get price balance
	var url_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-banlance-price')); ?>';
	function getBalancePrice(servce_id,student_id){
			dojo.xhrPost({
				url:url_balance,
				content:{
					'servce_id':servce_id,
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					
					  if(data){
						  dijit.byId('tuitionfee').attr('value',data.price_fee);
						  dijit.byId('ids').attr('value',data.id);
						  dijit.byId('total').attr('value',data.price_fee);
						  dijit.byId('books').attr('value',data.price_fee);
						  dijit.byId('not').attr('value',data.sms);
						 
					 }else {
						 dijit.byId('ids').attr('value','');
						// paymentTerms();
						 dijit.byId('tuitionfee').attr('value','0'); 
						 dijit.byId('total').attr('value','0'); 
						 dijit.byId('discount').attr('value','0');
						 dijit.byId('books').attr('value','0');
						 dijit.byId('remaining').attr('value','0');
						 dijit.byId('remark').attr('value','0');
						 //dijit.byId('char_price').attr('value','0');
						 dijit.byId('not').attr('value','');
					  }
				},
				error: function(err) {
					alert(err);
				}
			});
	}

	function setID(){
		stu_id = dijit.byId('old_stu_name').get('value');
		dijit.byId('old_studens').attr('value',stu_id);
	}

	///get gep old student
	var url_getGepoldstudent = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-gep-old-student')); ?>';
	function getGepOldStudentById(){
		student_id=dijit.byId('old_studens').get('value');
		dijit.byId('old_stu_name').attr('value',student_id);
			dojo.xhrPost({
				url:url_getGepoldstudent,
				content:{
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					  if(data){
						dijit.byId('kh_name').attr('value',data.stu_khname);
						dijit.byId('en_name').attr('value',data.stu_enname);
						dijit.byId('sex').attr('value',data.sex);
						dijit.byId('dept').attr('value',data.degree);
						getallModel(data.degree,data.grade);
						//dijit.byId('grade').attr('value',data.grade);
					  }else {
						alert('Student Id not found!');
						dijit.byId('kh_name').attr('value','');
						dijit.byId('en_name').attr('value','');
						dijit.byId('sex').attr('value','');
						dijit.byId('dept').attr('value','');
						dijit.byId('grade').attr('value','');
					  } 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
</script>