<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate("EDIT_OTHER_INCOME")?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/form/SimpleTextarea"]);
 </script>
<form id='frm_other_income' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'income','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
			cate_income = dijit.byId('cate_income').get('value')
			if(cate_income==0 || cate_income==-1){
				alert("Please select category income !!! ");
				dijit.byId('cate_income').focus();
				return false;
			}

			branch_id = dijit.byId('branch_id').get('value')
			if(branch_id==0 || branch_id==-1){
				alert("Please select branch !!! ");
				dijit.byId('branch_id').focus();
				return false;
			}

			return true;
		}else {
			return false;
		}
	</script>
	
	<fieldset>
		<legend style="text-align: center;font-size:18px;"><strong><?php echo $tr->translate("ADD_OTHER_INCOME")?></strong></legend>
		<table cellspacing="10"  width="100%" border="0">
			<tr>
				<td width="45%">
					<table width="100%" cellspacing="5" cellpadding="10">
						<tr>
							<td width="20%"><?php echo $tr->translate("BRANCH");?></td>
							<td width="80%"><?php echo $frm->getElement('branch_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME")?></td>
							<td><?php echo $frm->getElement('name');?></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php echo $frm->getElement('sex');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php echo $frm->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('Description');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('Stutas');?></td>
						</tr>
						
					</table>
				</td>
				
				<td width="5%">&nbsp;</td>
				
				<td width="50%">
					<table width="100%" cellspacing="5" cellpadding="10" style="white-space:nowrap;">
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO")?></td>
							<td width="80%"><?php echo $frm->getElement('invoice');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CATEGORY_INCOME")?></td>
							<td><input id="cate_income" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("INCOME_TITLE")?></td>
							<td><?php echo $frm->getElement('title');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TOTAL_INCOME")?>($)</td>
							<td><?php echo $frm->getElement('total_amount');?></td>
						</tr>
						<tr>
							<td colspan="2">
								<input type="text" class="fullside" name="readmoney" readonly id="readmoney" dojoType="dijit.form.TextBox" />
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("FOR_DATE")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="3" align="center">
				
					<input type="submit" label="<?php echo $tr->translate("SAVE_CLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
						 iconClass="dijitIconDelete"/>
						 
					<input type="submit" label="<?php echo $tr->translate("SAVE_NEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
						 iconClass="dijitIconNewTask"/>
						 
					<input type="button" label="<?php echo $tr->translate("PRINT")?>" name='print' value='print' dojoType="dijit.form.Button"
						iconClass="dijitIconNewTask"  onclick="printIncome('');"   />	 
				</td>
			</tr>	
		</table>
	</fieldset>
</form>

<script type="text/javascript">
 
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.store.Memory");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.SimpleTextarea");

var cate_income_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->cate_income));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: cate_income_store,
		autoComplete: true,                        
		required: true,                      
	    id: "cate_income",
	    name: "cate_income",  
	    tabindex: "1",  
	    value:0,       
	    class: 'fullside',  
	    placeHolder:"Selecte Category", 
	    onChange: function() {          
		   	service_id = dijit.byId('cate_income').get('value');
		    if(service_id==-1){
		   		dijit.byId("popup_cate").show();
		    }
	   }
	}, "cate_income");
	dijit.byId('cate_income').attr('value','<?php echo $this->row['cat_id']?>');

	readMoneyInKhmer();
	setReadonlyPageEdit();
});

	function setReadonlyPageEdit(){
		dijit.byId("branch_id").set('readOnly',true);
		dijit.byId("title").set('readOnly',true);
		dijit.byId("invoice").set('readOnly',true);
		dijit.byId("cate_income").set('readOnly',true);
		dijit.byId("total_amount").set('readOnly',true);
		dijit.byId("Description").set('readOnly',true);
		dijit.byId("Date").set('readOnly',true);
		
		dijit.byId("name").set('readOnly',true);
		dijit.byId("sex").set('readOnly',true);
		dijit.byId("phone").set('readOnly',true);
	}
	
	function getValue(){
		cate_id = dijit.byId('cat_income').get('value');
		if(cate_id==-1){
			dijit.byId("popup_cate").show();
		}
	}

	var url_add_cate_income = '<?php echo $this->url(array("module"=>"registrar","controller"=>"income","action"=>"add-cate-income")); ?>';
	function addCateIncome(){
		if(dijit.byId('frm_add_cate_income').validate()) {
			dojo.xhrPost({
				url:url_add_cate_income,
				form: dojo.byId("frm_add_cate_income"),
				handleAs:"json",
				load: function(data) {
					//alert(data); 
					var Itemmake = { 
							id: data,
							name: dijit.byId('cate_title').get('value')
						};
					addDataToSelectbox(dijit.byId('cate_income'), cate_income_store, Itemmake, data);
					dijit.byId('frm_add_cate_income').reset();
					hidePopup();
					
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	function getNewReceiptNo(){

	}
	function hidePopup(){		
		dijit.byId("popup_cate").hide();
	}

	function readMoneyInKhmer(){
		
		netTotal = (dijit.byId('total_amount').get('value')).toFixed(2);
		//netTotal = (isNaN(netTotal)?netTotal:0).toFixed(2);
		
		//alert(netTotal);
		
		var str = netTotal.toString();
		str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
		
		if(first_decimal>0){string='ដុល្លា និង ';last_string="សេន"}else{string="";str_cent="";last_string="ដុល្លា";}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
		first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
		last_money_decimal = read_in_khmer_from_0_to_9(last_decimal);
		money_khmer=read_money_in_khmer(netTotal);

		if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
		first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
		last_money_decimal_en = read_in_english_from_0_to_9(last_decimal);
		money_english=read_money_in_english(netTotal);
		
		//read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string;
		//read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )';
		
		dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string);
	}


	function printIncome(){
		if(dijit.byId('frm_other_income').validate()) {
		
		//////////////////////////////////// check validate ///////////////////////////////
			cate_income = dijit.byId('cate_income').get('value')
			if(cate_income==0 || cate_income==-1){
				alert("Please select category income !!! ");
				dijit.byId('cate_income').focus();
				return false;
			}

			branch_id = dijit.byId('branch_id').get('value')
			if(branch_id==0 || branch_id==-1){
				alert("Please select branch !!! ");
				dijit.byId('branch_id').focus();
				return false;
			}
		///////////////////////////////////////////////////////////////////////////////////	
			
			
			dojo.byId("lb_name").innerHTML = dijit.byId('name').get('value');
			dojo.byId("lb_sex").innerHTML = dijit.byId('sex').attr('displayedValue');
			dojo.byId("lb_phone").innerHTML = dijit.byId('phone').get('value');
			
			dojo.byId("lb_readmoney").innerHTML = dijit.byId("readmoney").attr('displayedValue');
			
			dojo.byId("lb_receipt_type").innerHTML = "Other Income";

			dojo.byId("lb_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
			
			dojo.byId("lb_receipt_no").innerHTML = dijit.byId('invoice').get('value');
			
			cate_income = dijit.byId('cate_income').get('value');
			if(cate_income==0){
				dojo.byId("lb_cate_income").innerHTML = "";
			}else{
				dojo.byId("lb_cate_income").innerHTML = dijit.byId("cate_income").attr('displayedValue');
			}
			
			dojo.byId("lb_title").innerHTML = dijit.byId("title").get('value');


			dojo.byId("lb_total_income").innerHTML = "$ "+dijit.byId("total_amount").get('value').toFixed(2);
			/*
			var d = dijit.byId("Date").get('value');
			 if(d!=null){
				 var day = d.getDate();
				 var mon = d.getMonth() + 1;
				 if(mon>=10){

				 }else{
					mon = "0"+mon;
				 }
				 var year = d.getFullYear();
				 dojo.byId("lb_date").innerHTML  = day+'/'+mon+'/'+year;
			 }else{
				 dojo.byId("lb_date").innerHTML  = '';
			 }
			 */
			dojo.byId("lb_note").innerHTML = dijit.byId("Description").get('value');
			dijit.byId("terms").show();	
		}
	}

	function printSubmit(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('PrintIncome').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
		$('#frm_other_income').submit();
		dijit.byId("terms").hide();	//hideDialog();
	}

	function hideDialog() {
		dijit.byId("terms").hide();
	}
</script>

<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:24cm;height: 14cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'" id="terms" >
		
		<div id="PrintIncome" style="width: 20cm !important; height: 11cm ; padding: 0px; margin-bottom:30px; ">
			<table width="100%" height="49%" class="print" cellspacing="0"  cellpadding="0" style="white-space:nowrap;">
				<tr>
					<td colspan="10" valign="top">
						<table width="100%" border="0" cellspacing="10" style="font-family: Khmer OS Battambang;font-size:16px;white-space:nowrap;line-height: 20px;">
							<tr>
							    <td colspan="4"  align="center" style="">
									<table width="100%" border="0" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-15px;font-weight:bold;">
										<tr>
											<td width="25%" align="left" style="font-size:12px;">
												<div style="font-size:17px;"><label id="lb_branch" style="color:#000;font-size:15px;"> </label></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
											</td>
											<td width="50%" align="center">
												<img style="width: 30%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td width="25%" align="center" style="font-size:15px;color:red;"><label id="lb_receipt_type" style="color:#000;font-size:17px;"> </label><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
										</tr>
									</table>
							    </td>
							</tr>
							<tr >
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -30px;">
										<tr>
											<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
											<td width="20%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
											<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
										</tr>
									</table>
								</td>
							</tr>
							<style>
								.h{ margin-top: -3px;margin-bottom: 3px;}
								.tab_row{ margin-top: -8px;}
								
								.h1{ margin-top: -6px;}
								.values{ min-height: 20px; padding: 0 5px;display: block;
										 font-family: Khmer OS battambang ,Times New Roman;}
								.fonteng{font-size:16px;}
								.one{white-space:nowrap;font-size:14px;text-align:center;}
								.border{border:1px solid #000; min-width:220px}
								.underline{margin-top: -18px;text-align:center;}
							</style>
							
							<tr >
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top:-15px;">
										<tr>
											<td width="10%">
												ឈ្មោះអ្នកបង់ប្រាក់
											</td>
											<td width="30%">
												<label class="values one" id="lb_name" ></label>
												<div class="underline">................................................................................</div>
											</td>
											<td width="5%" align="center">
												ភេទ 
											</td>
											<td width="10%" align="center">
												<label class="values one" id="lb_sex" ></label>
												<div class="underline">..............</div>
											</td>
											<td width="10%" align="center">
												លេខទូរសព្ទ
											</td>
											<td width="35%">
												<label class="values one" id="lb_phone" ></label>
												<div class="underline">....................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top:-15px;">
										<tr>
											<td width="10%">
												សម្គាល់
											</td>
											<td width="30%">
												<label class="values one" id="lb_note" ></label>
												<div class="underline">.............................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="4" style="border:1px solid #000;">
									<table width="100%" style="white-space:nowrap;">
										<tr>
											<td width="100%">
												<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
													<tr>
														<td width="15%">
															ប្រភេទចំណូល
														</td>
														<td width="85%">
															<label class="values one" id="lb_cate_income" ></label>
															<div class="underline">..................................................................................................................................................................................................</div>
														</td>
													</tr>
												</table>
											</td>
										</tr>
										
										<tr>
											<td width="100%">
												<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top:-5px;">
													<tr>
														<td width="15%">
															បរិយាយចំណូល
														</td>
														<td width="85%">
															<label class="values one" id="lb_title" ></label>
															<div class="underline">................................................................................................................................................................................................</div>
														</td>
													</tr>
												</table>
											</td>
										</tr>
										
										<tr>
											<td width="100%">
												<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top:-5px;">
													<tr>
														<td width="15%">
															ទឹកប្រាក់ទទួលបានសរុប
														</td>
														<td width="20%" style="border:1px solid #000;">
															<label class="values one" id="lb_total_income" />
														</td>
														
														<td width="65%">
															&nbsp;
														</td>
													</tr>
												</table>
											</td>
										</tr>
										
										<tr>
											<td width="100%">
												<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top:-5px;">
													<tr>
														<td width="15%">
															ទឹកប្រាក់ទទួលបានជាអក្សរ 
														</td>
														<td width="85%">
															<label class="values one" id="lb_readmoney" ></label>
															<div class="underline">..................................................................................................................................................................................</div>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:11px;font-family:Khmer OS Battambang, Times New Roman;margin-top:-12px;">
										<tr>
											<td width="70%">&nbsp;</td>
											<td width="30%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
										</tr>
									</table>
								</td>
							</tr>
							
							
							<tr>
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol Light, Times New Roman;margin-top:-20px;">
										<tr>
											<td width="25%" align="center">ប្រធានគណនេយ្យ/Accounting Manager</td>
											<td width="25%" align="center">អ្នកបង់ប្រាក់/Payer</td>
											<td width="25%" align="center">បេឡា/Cashier</td>
											<td width="25%" align="center">អ្នកផ្តល់ព័ត៌មាន​/Receiptionist</td>
										</tr>
										<tr>
											<td colspan="4" align="center">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="4" align="center">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="4" align="center">&nbsp;</td>
										</tr>
										<tr>
											<td align="center" style="font-size:12px;"></td>
											<td align="center"></td>
											<td align="center">
												<div style=" font-size: 12px;margin-top:-18px;"> 
													<?php 
													   $session_user=new Zend_Session_Namespace('auth');
													   $last_name=$session_user->last_name;
													   $username = $session_user->first_name;
													   echo $last_name." ".$username;
													?>
												</div>
											</td>
											<td align="center"></td>
										</tr>
										
										<tr>
											<td colspan="4" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="4">
									<table width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang, Times New Roman;margin-top:-37px;">
										<tr>
											<td valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
										</tr>
										<tr>
											<td colspan="2" valign="top" style=" ">
												- ប្រាក់ដែលបង់ហើយមិនអាចដកវិញបានឡើយ ។
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="printSubmit();"><?php echo $tr->translate("PRINT");?></button>
	</div>
</div>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_cate" >
		<form style="background-color: buttonface;" id='frm_add_cate_income' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TITLE")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="cate_title" id="cate_title" type="text" required="true" /></td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TYPE")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="type" id="type" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("INCOME")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" name="close" id="close" value="close" label="Close" dojoType="dijit.form.Button" onclick="hidePopup();" />
								<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCateIncome();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>
