<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_OCCUPATION')); 
	
	$rs=$this->rs;
?>

	<form  id='add_occupation' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			}else {
				return false;
			}
		</script>
		
		<fieldset style="width: 40%;margin: 0 auto;">
			<legend align="center"><strong><?php echo $tr->translate('EDIT_OCCUPATION');?></strong></legend>
			<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
				<tr>
					<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="id" name="id" value="<?php echo $rs["occupation_id"]?>" type="hidden"></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate('OCCUPATION');?></td>
					<td>
						<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="occu_name" name="occu_name" value="<?php echo $rs["occu_name"]?>" type="text">
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate('STATUS');?></td>
					<td>
						<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" class="fullside">
    						<option value="1" <?php if ($rs["status"]==1){echo "selected='selected'";}?> label="active" ><?php echo $tr->translate('ACTIVE');?></option>
    						<option value="0" label="deactive" <?php if ($rs["status"]==0){echo "selected='selected'";}?>  ><?php echo $tr->translate('DEACTIVE');?></option>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan="4" align="center">
						 <input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					 	 <input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</td>
				</tr>
				
			</table>
		</fieldset>
	</form>