<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate("EDIT_OTHER_INCOME")?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/form/SimpleTextarea"]);
 </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'income','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
			branch_id = dijit.byId('branch_id').get('value');
			if(branch_id==0 || branch_id==-1){
				alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?> !!! ");
				dijit.byId('branch_id').focus();
				return false;
			}
			cate_income = dijit.byId('cate_income').get('value');
			if(cate_income==0 || cate_income==-1){
				alert("<?php echo $tr->translate("PLEASE_SELECT_INCOME_CATE")?> !!! ");
				dijit.byId('cate_income').focus();
				return false;
			}
			loadingBlock();
			dijit.byId("save").attr("disabled",true);
			return true;
		}else {
			return false;
		}
	</script>
	<fieldset>
		<legend style="text-align: center;font-size:18px;"><strong><?php echo $tr->translate("EDIT_OTHER_INCOME")?></strong></legend>
		<table cellspacing="10" class='fullside' >
			<tr>
				<td width="45%">
					<table width="100%" cellspacing="5" cellpadding="10">
						<tr>
							<td width="20%"><?php echo $tr->translate("BRANCH");?></td>
							<td width="80%"><?php echo $frm->getElement('branch_id');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME")?></td>
							<td><?php echo $frm->getElement('name');?></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php echo $frm->getElement('sex');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php echo $frm->getElement('phone');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('Description');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('Stutas');?></td>
						</tr>
						
					</table>
				</td>
				
				<td width="5%">&nbsp;</td>
				
				<td width="50%">
					<table width="100%" cellspacing="5" cellpadding="10" style="white-space:nowrap;">
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO")?></td>
							<td width="80%"><?php echo $frm->getElement('invoice');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CATEGORY_INCOME")?></td>
							<td><input id="cate_income" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("INCOME_TITLE")?></td>
							<td><?php echo $frm->getElement('title');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TOTAL_INCOME")?>($)</td>
							<td><?php echo $frm->getElement('total_amount');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
							<td><?php echo $frm->getElement('payment_method');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAYIMENT_NOTE");?></td>
							<td><?php echo $frm->getElement('note_payment');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("FOR_DATE")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("វេន");?></td>
							<td>
								<select name="shift" id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
									<option value="1" <?php if($this->row['shift']==1){echo "selected='selected'";}?>>វេនទី1</option>
									<option value="2" <?php if($this->row['shift']==2){echo "selected='selected'";}?>>វេនទី2</option>
									<option value="3" <?php if($this->row['shift']==3){echo "selected='selected'";}?>>វេនទី3</option>
								</select>
							</td>
						</tr>
						<tr>	
							<td colspan="2" align="right"><?php echo $this->row['create_date'];?></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="3" align="center">
					<input type="submit" label="<?php echo $tr->translate("GO_EDIT");?>" id="save" dojoType="dijit.form.Button"
						 iconClass="dijitEditorIcon dijitEditorIconSave"/>
				</td>
			</tr>	
		</table>
	</fieldset>	
</form>

<script type="text/javascript">
 
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.store.Memory");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.SimpleTextarea");

var cate_income_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->cate_income));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: cate_income_store,
		autoComplete: true,                        
		required: true,                      
	    id: "cate_income",
	    name: "cate_income",  
	    tabindex: "1",  
	    value:0,       
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_CATEGORY");?>", 
	    onChange: function() {          
		   	service_id = dijit.byId('cate_income').get('value');
		    if(service_id==-1){
		   		dijit.byId("popup_cate").show();
		    }
	   }
	}, "cate_income");
	dijit.byId('cate_income').attr('value','<?php echo $this->row['cat_id']?>');
});

	function getValue(){
		cate_id = dijit.byId('cat_income').get('value');
		if(cate_id==-1){
			dijit.byId("popup_cate").show();
		}
	}

	var url_add_cate_income = '<?php echo $this->url(array("module"=>"registrar","controller"=>"income","action"=>"add-cate-income")); ?>';
	function addCateIncome(){
		if(dijit.byId('frm_add_cate_income').validate()) {
			dojo.xhrPost({
				url:url_add_cate_income,
				form: dojo.byId("frm_add_cate_income"),
				handleAs:"json",
				load: function(data) {
					//alert(data); 
					var Itemmake = { 
							id: data,
							name: dijit.byId('cate_title').get('value')
						};
					addDataToSelectbox(dijit.byId('cate_income'), cate_income_store, Itemmake, data);
					dijit.byId('frm_add_cate_income').reset();
					hidePopup();
					
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
	function hidePopup(){		
		dijit.byId("popup_cate").hide();
	}
 
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_cate" >
		<form style="background-color: buttonface;" id='frm_add_cate_income' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TITLE")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="cate_title" id="cate_title" type="text" required="true" /></td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TYPE")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="type" id="type" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("INCOME")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" name="close" id="close" value="close" label="Close" dojoType="dijit.form.Button" onclick="hidePopup();" />
								<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCateIncome();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>
